swisspost/design-system

packages/web-styles/gulpfile.js

Fixes the release workflow, which currently fails for the `web-styles` package because the publish command targets the `dist` folder, and `dist/package.json` points to `/dist/dist`, a directory that doesn't exist. Haven't looked into why looking for a `package.json` file in `dist/dist` doesn't produce an error, but transforming `dist/package.json` should fix the issue.
I have tried it out locally against `verdaccio` and `changeset publish` worked as expected. Feel free to close the PR if you have different plans for fixing the issue, I'm more interested in letting you know what went wrong.
Not 100% sure as to why `swisspost-intranet-header` doesn't have the same issue, but my guess is:
https://github.com/swisspost/common-web-frontend/blob/9203419db831f4eca3fca92b3f6b55194e0701e4/packages/a …

fix(web-styles): publish the `dist` subdirectory

---

.stylelintrc.js
packages/web-styles/package.json
pnpm-lock.yaml

Property sort order is not practical at this stage of development. It's more hindering than useful.

chore(linting): remove sort order plugin

---

.changeset/pink-dragons-carry.md
packages/web-styles/src/components/progress.scss

The Progressbar was nearly invisible, in Windows high-contrast-mode.
To activate this mode on Windows, click Alt + Shift + PrintScreen.

fix(styles): adds styles for progressbar in high-contrast-mode

---

.changeset/tall-moons-joke.md
packages/web-styles/src/mixins/_button.scss
packages/web-styles/src/variables/_type.scss
packages/web-styles/src/variables/components/_button.scss

- The button component has now his own font-size-map.
- The global font-size-map and its dependant variables ($font-size-map, $font-size-sm, $font-size-rg, $font-size-lg) have been removed.

chore(variables): Refactors button font-sizes and removes deprecated font-size-map

---

packages/web-styles/package.json

When starting Storybook a second time (after the cache has been created once before) from the console on Windows, an error occurs:
`[Error: EBUSY: resource busy or locked, open 'C:\GIT\swisspost\common-web-frontend\packages\web-styles\node_modules\.cache\storybook\dev-server\325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7'] { errno: -4082, code: 'EBUSY', syscall: 'open', path: 'C:\\GIT\\swisspost\\common-web-frontend\\packages\\web-styles\\node_modules\\.cache\\storybook\\dev-server\\325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7' }`
This PR is kind of a workaround, to get rid of this error. Not a real and proper solution.
For further informations visit: https://issuehunt.io/r/storybookjs/storybook/issues/13795.

build(storybook): fix storybook startup error

---

.changeset/curvy-starfishes-explain.md
packages/web-styles/.storybook/main.js
packages/web-styles/package.json

When starting Storybook from the console on Windows, change a story and then hit save, an error occurs.
It's the same error who occured when starting up storybook a second time (https://github.com/swisspost/common-web-frontend/pull/247):
[Error: EBUSY: resource busy or locked, open 'C:\GIT\swisspost\common-web-frontend\packages\web-styles\node_modules.cache\storybook\dev-server\325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7'] { errno: -4082, code: 'EBUSY', syscall: 'open', path: 'C:\GIT\swisspost\common-web-frontend\packages\web-styles\node_modules\.cache\storybook\dev-server\325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7' }
The solution (workaround) was found here and was submitted by andrewiggins: …

build(storybook): fix storybook onstartup and onsave error

---

.changeset/funny-actors-cough.md
packages/web-demo/src/app/bootstrap/components/alert/toast-demo/toast-demo.component.html
packages/web-demo/src/app/bootstrap/components/alert/toast-demo/toast-demo.component.ts

The ngx-toastr supports adding a close button to toast alerts. The button however is announced as 'Close' in front of the actual message. The text is always English and cannot be configured. Disabling the close button just reads the alert message/title which gives a little better UX.

docs(toastr): improve documentation with accessibility hint

---

.changeset/eight-pants-trade.md
packages/web-styles/src/components/intranet-header/_top-navigation.scss

The line-height of dropdowns inside a intranet-header component matches now the `line-height` of simple links.
This leads to equal heights for link- and dropdown-elements.
Furthermore, the invalid css-rule `background-color: none;` has been replaced with `background-color: transparent;`.

fix(intranet-header): Fix intranet-header styles

---

.changeset/calm-owls-ring.md
packages/web-demo/src/app/bootstrap/components/form-range/form-range-custom-demo/form-range-custom-demo.component.html

The change lets mobiledevices open a number-only keyboard, when selecting the inputfield. What simplifies data entry for the user.

fix(form-range): add inputmode for inputfield for controlled range value

---

.changeset/thin-horses-divide.md
packages/web-demo/src/app/ng-bootstrap/components/popover/popover-demo/popover-demo.component.html

Included a popover example with markup (e.g. link) and improved the gaps between the buttons.
The original error message is outdated. Links are framed with a browserspecific outline when they are focused.
**Chrome**
**Firefox**

fix(popover): add popover example with markup

---

packages/web-demo/src/app/bootstrap/components/form-select-multiple/form-select-multiple-demo/form-select-multiple-demo.component.html
packages/web-demo/src/app/bootstrap/components/form-select-multiple/form-select-multiple-demo/form-select-multiple-demo.component.scss
packages/web-demo/src/app/bootstrap/components/form-select-multiple/form-select-multiple-demo/form-select-multiple-demo.component.ts

The size attribute only works correctly from 4+ items in Safari. This is a known issue (https://stackoverflow.com/questions/15760089/select-size-attribute-size-not-working-in-chrome-safari).

docs(multiple-select): update documentation on the size attribute

---

packages/web-styles/src/placeholders/_notifications.scss

Alerts with custom icons face the problem that those icons are black. Inversion techniques don't work because it would invert the whole alert. Creating white alternatives for all possible icons would blow up CSS size too much with current approaches so it's not viable. This approach just replaces custom icons with the default alert icon. This way, only a small set of white icons has to be created.

fix(alert): icons in high contrast mode

---

.changeset/poor-games-know.md
packages/styles/src/components/utilities.scss

To avoid different stylings in different browsers, links and there pseudo classes (visited, focus, hover) have been overwritten with the css statment: `color: LinkText !important;`.

fix(links): add hcm styles

---

.changeset/tidy-tomatoes-help.md
packages/styles/src/components/intranet-header/_sidebar.scss

On mobile devices the sidebar showed an unnecessary pseudo-element (when the menu was opened).
This pseudo-element has been removed.

fix(intranet-header): remove unnecessary pseudo-element

---

.changeset/hip-geese-push.md
packages/styles/src/components/forms.scss

I was able to eliminate almost all of the graphical errors.
Unfortunately this leads to the fact that you have to set the button translations via content CSS-property and these are dependent on the document-language.
The integrated languages are: en (default), de, fr, it

fix(input-file): Fix display errors on safari

---

.changeset/young-mayflies-smoke.md
packages/demo/src/app/bootstrap/components/form-control/form-control-demo/form-control-demo.component.html
packages/styles/src/components/floating-label.scss
packages/styles/src/variables/components/_forms.scss

The following form controls have been adjusted:
- input
- select
- input[type="file"]
- textarea
In connection with the revision, the following superfluous scss variables were removed from the project:
- $form-floating-label-padding-t
- $form-floating-label-padding-b
- $form-floating-textarea-line-height
- $form-floating-textarea-padding-t
- $form-floating-textarea-padding-b

feat(form-control-lg, form-floating)!: make form-controls even height

---

.changeset/spotty-badgers-brake.md
packages/styles/src/components/form-control.stories.js

- Created a story for the form control styles
- Documented the possible arguments
- Made sure the code snippet can be used as-is in a project
- Found a misalignment of the floating labels when used with a form control that has validation and/or hinting and created the bug ticket #559 to fix the issue

feat(styles): add form control story

---

.changeset/unlucky-insects-do.md
packages/demo/src/app/home/home.component.html

Switched to displaying the styles package version number instead of the demo app version number. The styles version is more important to developers than thenow disconnected demo version number

chore(demo): switched to styles version number

---

.github/actions/artifact-download/action.yaml
.github/actions/deploy-to-netlify/action.yaml
packages/demo/src/app/common/highlight.provider.ts

According to this post https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/, the set_output can be replaced by the newer env file approach.

build(actions): fix deprecated set_output

---

.changeset/forty-pillows-cross.md
packages/demo/src/app/home/home.component.html

Updated the target Angular version to 14 in the migration instructions. The Intranet Header is not compatible with older versions.

fix(demo): update target Angular version to 14

---

.github/CODEOWNERS
.prettierignore

Adds maintainers as codeowners so they will be requested for review on every pull request. This is something we have to do manually at the moment.

chore: add a github codeowners file

---

.vscode/settings.json

These instructions are not very useful at the moment and not everybody is using the same IDE. We already have a editorconfig in the root for the most basic settings, everything else would be up to the dev. Correct linting is enforced with the PR check.

chore: remove IDE specific instructions

---

.github/workflows/release.yaml

The old check only checked if any package got released to npm, which is not the case if the only the documentation got updated. This did not trigger a deploy of the documentations. The intended behaviour was to check if the demo package.json version has changed and do a release then.

build(release): check if package version updated for docs deploys

---

.changeset/three-apricots-cheat.md
packages/changelog-github/src/index.ts

The <sup> construct does not work as intended in most contexts, adding unnecessary and confusing spacing into changelogs. New intended format:
- This is a contribution. (by username with [#111](https://github.com/swisspost/design-system/issues/111))
- This is a multiline contribution that needs
a lot of text (by username with [#111](https://github.com/swisspost/design-system/issues/111))

fix: use parens for attributions

---

.changeset/stale-buses-lie.md
packages/styles/src/components/datepicker.scss

When outside days get hidden, they collapse in their flex context and change the alignment of the first days of the month. Adding flex-grow 1 ensures the hidden days still keep their space so the day labels on top match correctly with the calendar days.

fix(datepicker): alignment of days when outside="hidden"

---

.changeset/slow-tables-kick.md
packages/demo/src/app/intranet-layout/intranet-layout.component.html
packages/demo/src/app/intranet-layout/intranet-layout.component.ts

Adds import instructions for the intranet-header component because I stumbled upon it myself earlier.

feat(documentation): add import instruction to intranet header documentation

---

.changeset/light-hairs-turn.md
packages/styles/src/mixins/_utilities.scss

Sass seems not entirely ready for :is. When integrating in another project, this mixin causes sass to silently fail and generate an empty output. The bug is not recreatable in a different environment and therefore we could not raise an issue with sass (yet).

fix(styles): unwrap complex :is selector

---

.changeset/hot-dryers-bathe.md
packages/internet-header/src/components/post-internet-breadcrumbs/post-internet-breadcrumbs.tsx

The iframe resize plugin does not correctly resize the cross origin iframe if the checks are active. Also removed unnecessary logs along the way.

fix(internet-header): disable origin check

---

.changeset/cool-colts-tell.md
packages/documentation/cypress/e2e/search.cy.ts
packages/internet-header/src/components/post-search/post-search.tsx

Patched relative URLs for the "most searched services" feature of the search box. Relative URLs are always resolved to the base "https://post.ch"

fix(internet-header): patched relative URLs in search recommendations

---

.github/workflows/build-documentation.yaml

This lets the documentation build workflow run when internet header files have changed, enabling PR previews for this package as well.

chore: build docs when internet header is updated

---

.changeset/unlucky-moons-march.md
packages/documentation/.storybook/preview.scss

Headings for the docs have been styled in a way that affected headings inside components. To prevent this, a more specific selector is being used now.

fix(docs): style headings more specifically

---

renovate.json

In an effort to reduce the amount of PRs created by renovate, I'd like to test the group all non-major updates policy. This should create just one PR for all minor and patch updates which is much easier to merge on Monday.

chore: group non-major updates

---

.changeset/happy-scissors-turn.md
packages/internet-header/package.json
packages/styles/src/components/floating-label.scss

Fixed an issue with floating labels on input fields that prevented the label from being truncated correctly if it was overflowing the text box.

fix(styles): floating labels should be truncated

---

renovate.json

Angular schematics had a regression where utils are no longer exposed in versions newer than 15.0.4. Fixing Angular packages in the styles package does not have an impact on the supported version of Angular by the styles itself.

chore: add renovate rule to fix angular for styles

---

.changeset/clever-fans-remember.md
packages/demo/src/app/bootstrap/components/alert/alert-demo-page/alert-demo-page.component.html

Deprecated the `alert-error` and the `alert-notification` variants of the alert component. These variants will be removed in the next major version.

chore: deprecate alert-error and alert-notification

---

.changeset/smooth-pants-argue.md
packages/documentation/src/stories/components/alert/alert.stories.tsx
packages/styles/src/components/alert.scss
pnpm-lock.yaml

Decoupled the fixed and the action button styles for the alert component. Alerts can now be fixed to bottom without having action buttons and can have action buttons without being fixed to the bottom of the page.

feat(styles): decouple fixed position and actions for alerts

---

.changeset/eleven-tigers-glow.md
packages/demo/src/app/home/home.component.html
packages/demo/src/app/post-sample/components/stepper/stepper-demo/stepper-demo.component.html
packages/styles/src/components/stepper.scss

Updated the markup for the stepper component in order to improve accessibility. Completed items now require the prefix "Complete" and incomplete steps are no longer links.

feat(stepper)!: Updated stepper markup

---

.changeset/plenty-jars-approve.md
packages/documentation/src/stories/components/button-group/button-group.stories.tsx

Empty key values break storybook control rendering and lead to navigation hiccups. Using a default here is better because it's the correct class. The field is initially empty, so the default state without explicit class is still documented, only when size: md is explicitly chosen, the class will show up in the code block.

fix(docs): use btn-md instead of empty string

---

.changeset/twenty-apples-allow.md
packages/internet-header/src/components/post-search/post-search.tsx

Fixed a bug where a shipment information in the search suggestions was not reset after the search query changed.

fix(header): shipment info in search suggestions not reset

---

.changeset/blue-geese-pretend.md
packages/demo/src/app/ng-bootstrap/components/tooltip/tooltip-demo-page/tooltip-demo-page.component.html
packages/demo/src/app/ng-bootstrap/components/tooltip/tooltip-demo/tooltip-demo.component.html

Updated the documentation for tooltips regarding the "auto" placement option which can be used to place the tooltip where it fits if there is not enough space for the initial placement.

fix(demo): add auto as default placement setting

---

packages/demo/src/app/common/dependency-link/dependency-link.component.ts
packages/demo/src/app/common/version.service.ts

While refactoring the versions.json, the remote versions were used in the DependencyLink component by mistake. Refactored the component to use the local package.json information instead of the remote versions.json information.

fix: use local version for dependency-links

---

.changeset/gorgeous-rockets-try.md
packages/components/package.json
pnpm-lock.yaml

Fixed package dependencies. Moved dependencies that are not being used in production to devDependencies in order to simplify and speed up the package install process.

fix: move non-production dependencies to devDependencies

---

package.json

In a pnpm monorepo, these rules must be added to the root `package.json` file and nowhere else.

chore: add pnpm peerDependencyRules to get rid of unmet- and missing peer warnings

---

.github/actions/setup-pnpm/action.yaml
package.json

Allow pnpm to update minor and patch versions, but not major. Updating major versions breaks things as well as specifying a fixed version.

chore: allow patch and minor pnpm updates

---

.changeset/proud-owls-beg.md
.vscode/settings.json
packages/components-angular/package.json
packages/components-angular/projects/intranet-header-showcase/src/app/app.component.html
packages/components-angular/projects/intranet-header-showcase/src/app/app.module.ts
packages/components-angular/projects/intranet-header/.eslintrc.json
packages/components-angular/projects/intranet-header/src/lib/swisspost-intranet-header.component.html
packages/components-angular/projects/intranet-header/src/lib/swisspost-intranet-header.component.ts

Fixed the auto-close behavior of optional dropdown content. Clicking links or routerLinks (<a> tags) now closes the dropdown as expected.

fix(intranet-header): close dropdown on link click

---

.changeset/young-brooms-push.md
package.json
packages/styles/src/components/floating-label.scss

A rendering issue in Safari clipped text input in a floating label input field where the floating label intersected with the current value of the input. Even having a transparent background, the input was invisible below the floating label. Setting the height of the floating label correctly fixes the rendering issue because now the label does no longer cover the value.

fix(styles): Safari display issue with floating labels

---

.changeset/tall-rats-flash.md
packages/internet-header/src/components/post-internet-breadcrumbs/post-internet-breadcrumbs.scss
packages/internet-header/src/components/post-klp-login-widget/widget-styles.scss
packages/internet-header/src/components/post-language-switch/components/post-language-switch-list.tsx
packages/internet-header/src/components/post-main-navigation/post-main-navigation.scss
packages/internet-header/src/components/post-skiplinks/post-skiplinks.scss
packages/internet-header/src/utils/_placeholders.scss
packages/internet-header/src/utils/utils.scss
packages/styles/src/mixins/_forms.scss

Fixed focus styles for links and buttons inside the navigation. Focus styles are now defined and uniform across browsers.
@josemanosalvas, please refer to https://github.com/swisspost/design-system/issues/1447#issuecomment-1573314555 for enabling tab navigation on Mac, it's not enabled by default. You can find links to the preview environment further down in the comments of this PR if you'd like to have a look at the fix before it's being merged. Feedback is welcome.

fix(header): uniform focus styles across browsers

---

.changeset/fast-carrots-turn.md
.github/workflows/build-demo.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml
.github/workflows/unit-tests.yaml
packages/demo/src/app/home/home.component.html

This is a fix for an older release. Upon successfully merging into release/v5, a new, separate publish PR should be created by the release action, targeting the release/v5 branch.
TODO (after testing if the release PR is created): Deploy old documentation

fix: update installation instructions for v5

---

.changeset/shaggy-students-shave.md
packages/demo/src/app/post-sample/components/stepper/stepper-demo/stepper-demo.component.html

Stepper links make no sense without being a link back to this step. A href or [routerLink] is needed anyways. Regression was added because of https://github.com/swisspost/design-system/pull/1317/files#r1153405992. A href attribute might be less missleading than an internal [routerLink].

fix(demo): add href to make link focusable

---

.changeset/empty-hats-mix.md
packages/documentation/src/stories/icons/getting-started.stories.mdx

Since the snippet to set the meta for icons now uses the path `/post-icons` instead or `/public/post-icons` the postinstall script must be updated.

fix(docs): update paths in the icons getting started page

---

.changeset/spotty-pants-count.md
packages/documentation/src/stories/internet-header/components/header/post-internet-header.stories.tsx
packages/internet-header/cypress/e2e/stickyness.cy.ts
packages/internet-header/src/components/post-internet-header/post-internet-header.tsx

The stickyness setting "full" should no longer be used because it uses up too much screen space.

fix(header): deprecate stickyness full

---

packages/internet-header/cypress/e2e/stickyness.cy.ts

After scrolling, wait for elements that should be in the viewoprt instead of just checking if some elements are not in the viewport. When just checking the latter, cypress runs the check during scroll and it's immediately successful so the next scroll is executed. If there is an element that should be there, cypress has to wait for the scroll to finish before the element appears.

test: update stickyness test

---

.changeset/weak-radios-switch.md
packages/internet-header/src/assets/js/klp-login-widget.js
packages/internet-header/src/components/post-language-switch/post-language-switch.scss
packages/internet-header/src/components/post-search/post-search.scss
packages/internet-header/src/components/post-search/post-search.tsx
packages/internet-header/src/utils/utils.scss

Removed the global relative styling for buttons and links that messed with the absolute positioning of the search button.

fix(header): search button position

---

.changeset/short-crabs-clap.md
packages/internet-header/cypress/e2e/search.cy.ts
packages/internet-header/cypress/support/prepare-story.ts
packages/internet-header/src/models/header.model.ts
packages/internet-header/src/services/search/coveo.service.ts

For some pages (PostAuto), the coveo suggestions deliver inaccurate results. Until indices for these pages are added to coveo, turning off suggestions is the preferred way to go.

feat(header): added isCustomSuggestionHidden switch

---

packages/documentation-v7/src/stories/misc/changelog.stories.mdx

* Replace react-markdown with ["native" markdown from Storybook.](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#importing-plain-markdown-files-with-transcludemarkdown-has-changed)
What's missing from the version 6 is the style "dark" (dark background color) on code elements. But this should be handled through style so that the color adapt to the current theme. Currently, the background stays dark when we switch the theme.
```mdx
<ReactMarkdown
rehypePlugins={[rehypeRaw]}
components={{
code({ node, inline, className, children, ...props }) {
const match = /language-(\w+)/.exec(className || '');
return !inline && match ? (
<Source language={match[1]} dark code={String(children).replace(/\n$/, '')} />
) : (
<code className={className} {...props}>
{children}
</code>
);
},
}} …
```

chore(documentation): migrate changelog page to v7

---

.changeset/cold-mails-shout.md
packages/internet-header/cypress/e2e/environment.cy.ts
packages/internet-header/cypress/fixtures/pages/uppercase-environment.html
packages/internet-header/src/assets/js/klp-login-widget.js
packages/internet-header/src/components/post-internet-header/post-internet-header.tsx
packages/internet-header/src/services/config.service.ts

When the environment parameter is not set in lowercase, mapping to internal sets fails. This causes errors in the Login Widget for the Settings URL as well as for coveo token mapping.

fix: converted environment to lowercase on initialization

---

packages/documentation-v7/src/stories/icons/components/icon.demo.stories.ts
packages/documentation-v7/src/stories/icons/components/icon.docs.mdx
packages/documentation-v7/src/stories/icons/search-icons/search-icons.blocks.tsx
packages/documentation-v7/src/stories/icons/search-icons/search-icons.docs.mdx

| Before  | After   |
|---|---|
|  ![Screenshot 2023-07-27 at 17-12-54 Icons _ Components _ Icon - Default ⋅ Storybook](https://github.com/swisspost/design-system/assets/12294151/23268d5a-a53f-4339-b1d9-d6d0dfeb59b5) |  ![Screenshot 2023-07-27 at 17-12-14 Icons _ Icon Component - Docs ⋅ Storybook](https://github.com/swisspost/design-system/assets/12294151/6e9bf3d0-48e2-4e78-b66d-e0acd56a8e8c) |

feat(documentation): Hide icons stories and rename docs pages

---

.changeset/polite-radios-train.md
packages/styles/src/mixins/_button.scss
packages/styles/src/variables/_commons.scss
packages/styles/src/variables/components/_button.scss

Following https://github.com/swisspost/design-system/issues/1571#issuecomment-1641942510 and discussion from today.
Updated:
* Padding
* Internal gap
* Border-radius
Figma: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=9096%3A36684&mode=dev

feat(styles): update buttons padding, gap and border-radius

---

packages/documentation-v7/.storybook/blocks/footer.tsx
packages/documentation-v7/.storybook/main.ts
packages/documentation-v7/.storybook/manager.ts
packages/documentation-v7/.storybook/preview.ts
packages/documentation-v7/package.json
pnpm-lock.yaml

For the moment, dark mode is not implemented for many components. Until it is, the docs look broken when dark mode is enabled. Therefore I suggest to default to light mode until design and a system is available for dark mode.

docs: use light mode per default

---

packages/components/.eslintrc.json
packages/components/tsconfig.eslint.json
packages/components/tsconfig.json
packages/internet-header/.eslintrc.json
packages/internet-header/tsconfig.eslint.json
packages/internet-header/tsconfig.json

Today, when building components and internet-header packages, we include test files in the build. This is unnecessary and in addition, it breaks the running test command when locally you have the dist folder generated, as those tests in dist are discovered by jest, but cannot be run.
Before, Stencil provided another way to exclude files and folders, but it was replaced:
https://github.com/ionic-team/stencil/commit/c18cb1f608c7c4668b081b94f292d1f8af721641

fix(components, internet-header): exclude tests and spec files from build

---

.github/actions/deploy-to-netlify/action.yaml

Netlify cli wants to select a site in CI builds. Trying to pass site ID on the deploy command instead of linking beforehand.
Error: https://github.com/swisspost/design-system/actions/runs/5848489770/job/15855837555#step:5:166

chore: update netlify command

---

packages/documentation-v7/src/stories/components/toast/toast.stories.ts

Fix style dependency with component title. It broke when we changed the stories from hidden to standard.

fix(documentation-v7): Stacked toast - Change style link to component title

---

.changeset/long-pumpkins-repeat.md
.changeset/serious-toes-speak.md
packages/demo/src/app/ng-bootstrap/components/datepicker/datepicker-demo-page/datepicker-demo-page.component.html
packages/demo/src/app/ng-bootstrap/components/datepicker/datepicker-simple/datepicker-simple-lg.component.html
packages/demo/src/app/ng-bootstrap/components/datepicker/datepicker-simple/datepicker-simple.component.html
packages/demo/src/app/ng-bootstrap/components/datepicker/datepicker-validation/datepicker-validation-lg.component.html
packages/demo/src/app/ng-bootstrap/components/datepicker/datepicker-validation/datepicker-validation.component.html
packages/demo/src/styles.scss
packages/styles/src/components/datepicker.scss

I let `.pi-calendar` coexist with `.pi-3203` for now and added a deprecation message.

fix(styles): missing calendar icon with named icon

---

packages/styles/gulpfile.js
packages/styles/package.json
packages/styles/src/components/badge.scss
pnpm-lock.yaml

Only copies changed files to dist. This will improve performance for development massively because vite reacted to every change in dist individually and before, every single sass file was copied to dist regardless if it changed or not. Also, map-icons creates a theoretical infinite loop and calling watch again is not necessary within the watch task.

chore: improve styles watch performance

---

.github/workflows/stale.yaml

More infos and settings at https://github.com/actions/stale. Marks issues and PRs as stale without closing them.

chore: mark old issues and pull requests as stale

---

packages/documentation/src/stories/components/blockquote/blockquote.snapshot.stories.ts

changes the render function from Default.render to meta.render as Default.render was no longer defined due to the PR for migrating blockquote-stories #1778

fix(documentation): fixes blockquote snapshot-test

---

packages/demo/src/app/common/dependency-link/dependency-link.component.ts

I used this snippet to work, but the catch is never called and it doesn't work when the cache is empty: https://developer.mozilla.org/en-US/docs/Web/API/Cache/put#examples
A more appropriate snippet is this one: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/match
https://github.com/mdn/content/pull/29202

fix(demo): caches match doesn't throw errors

---

packages/internet-header/.eslintrc.json
packages/internet-header/package.json
packages/internet-header/src/components/post-internet-breadcrumbs/post-internet-breadcrumbs.tsx
packages/internet-header/src/components/post-klp-login-widget/post-klp-login-widget.tsx
packages/internet-header/src/components/post-language-switch/post-language-switch.tsx
packages/internet-header/src/components/post-main-navigation/post-main-navigation.tsx
packages/internet-header/src/components/post-search/post-search.tsx
packages/internet-header/src/components/post-skiplinks/post-skiplinks.tsx
pnpm-lock.yaml

The package `@stencil/eslint-plugin` was deprecated in favor of `@stencil-community/eslint-plugin`
https://www.npmjs.com/package/@stencil/eslint-plugin

chore(internet-header): Replace @stencil/eslint-plugin with community edition

---

.changeset/four-gifts-watch.md
packages/documentation/src/stories/components/checkbox/checkbox.docs.mdx
packages/documentation/src/stories/components/checkbox/checkbox.snapshot.stories.ts
packages/documentation/src/stories/components/checkbox/checkbox.stories.ts
packages/documentation/src/stories/components/radio/radio.docs.mdx
packages/documentation/src/stories/components/radio/radio.snapshot.stories.ts
packages/documentation/src/stories/components/radio/radio.stories.ts
packages/styles/src/components/form-check.scss
packages/styles/src/components/form-validation.scss
packages/styles/src/variables/components/_form-check.scss
packages/styles/src/variables/components/_form-validation.scss

@rouvenpost I made all the feedback validation boxes smaller according to the mockups (for all variants, you can see them in snapshots). I was not sure if it was intended or not. Please let me know if it's not the case.
- [Checkbox mockups](https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7750%3A33879&mode=dev)
- [Checkbox documentation page](https://preview-2067--swisspost-design-system-next.netlify.app/?path=/docs/components-checkbox--docs)
- [Checkbox snapshots](https://preview-2067--swisspost-design-system-next.netlify.app/iframe.html?id=snapshots--checkbox&viewMode=story)
- [Radio mockups](https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7777%3A33876&mode=dev)
- [Radio documentation …

fix(styles): Small variants for checkbox and radio

---

packages/documentation/package.json
pnpm-lock.yaml

https://github.com/swisspost/design-system/pull/2063 introduces another `vite` package version (v4.4.11) which is not the same as the one behind Storybook (v4.4.7). It seems that there are incompatibilities as the `*.entry.js` files of the components packages are not built with this change.
This PR removes this `vite` package and the code relies on the sub-dependency `vite` package of storybook.

fix(documentation): Remove incompatible vite version

---

.changeset/six-hotels-sell.md
packages/components/stencil.config.ts
packages/internet-header/stencil.config.ts

Compress (and remove comments) for sass output of stencil web components

feat(components, internet-header): Compress embedded sass output on web components

---

packages/documentation/.storybook/main.ts
packages/documentation/package.json
pnpm-lock.yaml

As far as I know, the axe a11y addon for storybook is not used. This one of the biggest chunks so we should remove it.

fix(documentation): Remove unused a11y addon

---

.changeset/spicy-cougars-buy.md
packages/styles/gulpfile.js
packages/styles/src/mixins/_icons.scss

Currently, we autoprefix CSS compressed output files, but not SCSS files that can also be used through the packages.

chore(styles): Run autoprefixer on scss files

---

packages/documentation/src/stories/getting-started/styles/styles.docs.mdx

Fix bug introduced with https://github.com/swisspost/design-system/pull/1952

fix(documentation): Styles docs has MDX p

---

packages/components/cypress/support/commands.ts

Some of the earliest tests are failing in watch mode, so extend timeout from default 4s to 30s to avoid this issue (like we are doing it for e2e in storybook).

fix(components): add e2e timeout when trying to get component

---

pnpm-lock.yaml

https://github.com/swisspost/design-system/pull/2072 introduces some sub-dependencies changes similarly to the initial PR of this revert: https://github.com/swisspost/design-system/pull/2083. This breaks e2e tests for components and internet-header. `*.entry.js` files are not generated/copied to the documentation assets folder and creates a 404 when we try to use a web component.
For testing, I cherry-pick the commit of this PR to https://github.com/swisspost/design-system/pull/2140
Also upgrading to Stencil 4 (https://github.com/swisspost/design-system/pull/2116) does not fix this issue.

fix(e2e): Revert vite 4.11 upgrade

---

.github/workflows/snapshot-tests.yaml

We are using very little of our quota for snapshots (25'000). I think we can run the snapshots automatically on the release PR.

chore: automatically run snapshot tests on release pr

---

packages/styles/src/components/floating-label.scss

Intellij is reporting issues with this pattern to use scss variables inside native CSS calc function.
According to the SCSS doc, we should either use the SCSS calc function (which is the same as CSS calc, but support SCSS variable) or use interpolation: https://sass-lang.com/documentation/values/calculations/

fix(styles): Floating-label using scss var inside CSS calc function

---

.changeset/giant-teachers-shout.md
packages/components/package.json
packages/components/src/index.ts
packages/components/stencil.config.ts
packages/documentation/src/stories/getting-started/components/components-cdn-all.sample.html
packages/documentation/src/stories/getting-started/components/components-cdn-esm-all.sample.html
packages/documentation/src/stories/getting-started/components/components-cdn-esm-specific.sample.html
packages/documentation/src/stories/getting-started/components/components-js-all.sample.js
packages/documentation/src/stories/getting-started/components/components-js-specific.sample.js
packages/documentation/src/stories/getting-started/components/components-use-all.sample.js
packages/documentation/src/stories/getting-started/components/components.docs.mdx
packages/internet-header/package.json
packages/internet-header/src/index.ts
packages/internet-header/stencil.config.ts

This time without the breaking changes, which we had to revert the last time ;) #2208

fix: stencil empty output files

---

.github/actions/artifact-download/action.yaml
.github/actions/artifact-upload/action.yaml
.github/workflows/build-documentation.yaml
.github/workflows/deploy-documentation.yaml
packages/documentation/src/noop.txt

This change will centrally handle zipping and unzipping of build artifacts for faster upload/download. There is one catch to this PR: the download action always runs on the main branch (for security reasons) and cannot be tested, therefore the documentation publishing workflow fails for this PR. To actually test it, we'd need to merge this PR and push a change to the documentation.

chore: zip build artifacts

---

packages/documentation/src/stories/components/input/input.docs.mdx
packages/documentation/src/stories/icons/search-icons/search-icons.blocks.tsx

Related to https://github.com/swisspost/design-system/issues/1811

fix(documentation): add placeholder to search for icons docs and document it

---

.changeset/clean-files-wonder.md
packages/documentation/.storybook/blocks/footer.tsx
packages/documentation/.storybook/blocks/layout.tsx
packages/documentation/src/stories/components/input/input.docs.mdx
packages/documentation/src/stories/icons/search-icons/search-icons.blocks.tsx
packages/documentation/src/stories/icons/search-icons/search-icons.docs.mdx
packages/documentation/src/stories/icons/search-icons/search-icons.stories.ts
packages/documentation/src/stories/misc/changelog/changelog.docs.mdx
packages/documentation/src/stories/misc/changelog/changelog.stories.ts

Fix Changelog and search for icons page after https://github.com/swisspost/design-system/pull/2132. If `storyIdToCSFFile` is not defined for example on docs page without stories attached, it breaks the whole page.

fix(documentation): edit on Github breaks page without stories attached

---

.github/actions/artifact-download/action.yaml

When a name is defined, the artifact is being unzipped at the root. Tested here https://github.com/gfellerph/artifact-test/actions.

chore: fix artifact path

---

.changeset/big-carrots-join.md
packages/documentation/src/stories/components/badge/badge.stories.ts

###
Remove unneeded badge size class at wrapper level to match https://design-system.post.ch/#/bootstrap-samples/badge

fix(documentation): remove unneeded badge size class

---

.changeset/cuddly-otters-compete.md
packages/styles/src/components/datepicker.scss

fix(styles): Datepicker year select overflow

---

.changeset/nasty-spies-explain.md
packages/styles/src/components/intranet-header/_sidebar.scss

This was tested on a side project. The issue is not visible in https://design-system.post.ch/#/post-samples/intranet-layout because the components styles have been rewritten to be used inline (position fixed was removed). It would be nice to rewrite this demo by using iframe instead, but it's too much work for the deprecated old design system doc.

fix(styles): Intranet-header sticky nav prevents interactivity

---

packages/components/package.json
packages/documentation/package.json
pnpm-lock.yaml

We had the same issue some weeks ago. e.g. in this PR: https://github.com/swisspost/design-system/actions/runs/6785015221/job/18442967411?pr=2065#step:5:19
And we fixed with: https://github.com/swisspost/design-system/pull/2238/files#diff-4ade8993db0ab98cef66268e7a71355b158eefa4db4a3e03f623638800612980
But it came back, and it seems it's linked to `createJestPuppeteerEnvironment`. I've found a PR and an issue on stencil/ionic side which seems to indicate that we need Puppeteer: https://github.com/ionic-team/ionic-framework/pull/28529#discussion_r1394451290 https://github.com/ionic-team/stencil/issues/4526
Tested successfully in this PR: https://github.com/swisspost/design-system/actions/runs/7043980625/job/19170759773?pr=2320

fix(components): stencil unit test require puppeteer

---

packages/icons/src/utilities/downloadSVG.ts

This eliminates accidental white space in the icon name.

fix(icons): trim file name before writing to disk

---

.changeset/pink-tomatoes-cross.md
packages/internet-header/src/components/post-internet-breadcrumbs/post-internet-breadcrumbs.scss

When we click or focus the close button of the help overlay in the internet-header breadcrumbs, the button moves to the left. This is due to this change : https://github.com/swisspost/design-system/blob/a9997e3ec66914cc94c5ae824918fbe4e052dca3/packages/internet-header/src/utils/_placeholders.scss#L22-L45
Visible on the portal: https://places.post.ch/recherche-de-site?shortcut=fr-sites
https://github.com/swisspost/design-system/assets/12294151/2c5bfd4d-0bc6-4c17-af52-517afbf94144

fix(internet-header): Close button on click or on focus in the help overlay moves

---

.github/workflows/release.yaml

This will prevent changesets from starting to release packages and then failing because of an invalid setup on one of the packages. Early failure will prevent some packages from being published without the complete workflow to finish (pushing git tags, notifying teams channel).

chore: dry run publish before starting to release

---

pnpm-lock.yaml

Run 
```
pnpm dedupe
pnpm update "@storybook/*
```
to update storybook to latest peer dependency, especially [vite to v5 which is supported since Storybook 7.5.](https://storybook.js.org/blog/storybook-7-5/) We may see also better performance

fix(documentation): Vite XSS vulnerability in 4.4.7

---

.changeset/polite-suns-promise.md
packages/internet-header/src/index.html
packages/internet-header/src/utils/scrollparent.ts

Scroll events don't fire on the body element if the window is scrolled, that prevented the stickiness functionality on most implementations to work properly.

fix(header): return correct scrollparent

---

.github/workflows/release.yaml
package.json

Bootstrapping can be done earlier to skip some steps in the release process and make the publish check work (all packages need to be built for this).

chore: bootstrap before checking the publish command

---

.changeset/perfect-ads-type.md
packages/components/stencil.config.ts
packages/documentation/src/stories/components/icons/search-icons/search-icons.styles.scss

Enabled import injection for components. This fixes an issue with importing dynamically loaded web components with the vite compiler for storybook.

chore(components): enable import injection

---

packages/documentation/vite.config.js

All docs e2e checks are failing at the moment. My suspicion is the following line where Vite discovers dependencies to optimize (Common js) after the first load, which ends up by reloading the page and failing some tests: https://github.com/swisspost/design-system/actions/runs/7530101061/job/20495763555?pr=2496#step:7:95

fix(e2e): Tests are failing because the docs takes too much time to load

---

.changeset/blue-bottles-sing.md
packages/documentation/src/stories/components/icons/components/icon.stories.ts

- Fix duplicate `flip-h` and `flip-v` argument
- Change category to make it work with how `flip-h` and `flip-v` are translated from plugin
- Remove args with falsy value so we don't display them at all. Before you could have `animation="null"` or `base=""`

fix(docs): Clean icon component controls from duplicate and null values

---

.github/workflows/deploy-demo.yaml
.github/workflows/deploy-documentation.yaml
packages/documentation/src/stories/components/accordion/accordion.docs.mdx

It seems that we need to use  @swisspost/design-system-demo and  @swisspost/design-system-documentation for it to work

fix(deploy): change  package name in filter

---

packages/internet-header/src/components/post-klp-login-widget/widget-styles.scss

Since the issue is not easily reproducible, because you would have to be logged in, I just fixed it in the dev tools on the live site and put it in the code.

feat(internet-header): focus on klp-widget links obscured fix

---

.github/workflows/e2e-tests.yaml

This is the recommended way to run cypress in parallel: https://docs.cypress.io/guides/continuous-integration/introduction#Xvfb
This was tested successfully in https://github.com/swisspost/design-system/actions/runs/7889393329/job/21529150647?pr=2552

chore(e2e): Fix Cypress issue with xvfb

---

.github/workflows/e2e-tests.yaml

Follows https://github.com/swisspost/design-system/pull/2637
In the recommandation, we should also kill the xvfb server after using it: https://docs.cypress.io/guides/continuous-integration/introduction#Xvfb
I thought that it didn't make sense as it's a virtual machine, but perhaps it makes sense, especially when we re-trigger a failed workflow. 
In this PR (where it works the first time I changed the worfklow) after a second run I got the following error: 
```
(EE) Server is already active for display 100
```
https://github.com/swisspost/design-system/actions/runs/7899925921/job/21561150669
It looks like cypress tried to run another server on another port (100 instead of 99) so it might confirm that it's needed. At least next run works with it: …

chore(e2e): Fix Cypress issue with xvfb 2

---

packages/components/package.json
packages/styles/package.json
pnpm-lock.yaml

This does not seem to be used anywhere, thus can be removed.

chore: remove npm-run-all2

---

.changeset/perfect-grapes-care.md
packages/components/cypress.config.js
packages/components/src/components/post-popover/post-popover.tsx
packages/components/src/components/post-popover/readme.md
packages/components/src/components/post-popovercontainer/post-popovercontainer.tsx
packages/components/src/components/post-tooltip/post-tooltip.tsx
packages/components/src/utils/attribute-observer.ts

This small timeout prevents the popovercontainer from opening and closing with the same event chain. This happens for example when the popover is open and the trigger button is clicked again. It's because first, an outside click is registered the popover closes. Right after that, the click from the toggle button fires and opens the popover again.

fix(popovercontainer): prevent immediate re-toggle

---

renovate.json

We're usually not able to update minor/patch versions of bootstrap without additional effort, therefore updates for bootstrap should be submitted in separate PRs.

chore: exclude bootstrap from minor/patch renovate grouping

---

packages/documentation/src/stories/components/alert/alert.docs.mdx

Very nitpick change, but self-closing doesn't exist with Custom Elements, so let's remove this ambiguity.

fix(documentation): Nitpick on <post-alert/> self closing

---

.changeset/rare-shoes-serve.md
packages/documentation/src/stories/foundation/color/color.blocks.tsx
packages/documentation/src/stories/foundation/color/color.styles.scss

Sometimes, it's nice to be able to have quick access to color value and be able, for example to compare with the design or some other places

feat(documentation): Display color value after color title for quick comparison

---

.changeset/short-singers-lay.md
packages/documentation/cypress/e2e/components/input.cy.ts
packages/documentation/cypress/e2e/components/range.cy.ts
packages/documentation/cypress/e2e/components/select.cy.ts
packages/styles/src/components/floating-label.scss
packages/styles/src/variables/components/_form-validation.scss
packages/styles/src/variables/components/_forms.scss

I didn't remove color-contrast rules for several elements, as it will be handled on other tickets:
* Radio and checkbox: https://github.com/swisspost/design-system/issues/2681
* Switch: https://github.com/swisspost/design-system/issues/853
* Textarea: https://github.com/swisspost/design-system/issues/1055

fix(styles): Color-contrast on form elements valid form-feedback

---

.changeset/pink-carpets-bathe.md
packages/components/cypress/e2e/tabs.cy.ts
packages/styles/src/components/tabs/_tab-title.scss
packages/styles/src/components/tabs/_tabs-wrapper.scss

1. Fixed color-contrast of post-tabs on dark-background:
From
To 
2. Added cursor pointer to tabs title
3. Revert change from https://github.com/swisspost/design-system/pull/2349/files/344934ab280122c643d2886666f3981829ff2ff1#r1413888274 and fix with added spacing. The margin is visible here: 
Note: @rouvenpost @Cian77 I didn't implement what's in the design https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=70-18&mode=design&t=VxSxr2DejdjVc4mY-0 because it misses how it should look like on dark colored background and because we are quite limited at the moment with this `post-tabs` component as the `:host-context` selector is not available (and will never be it seems) on all browsers, so to adapt to a particular theme given by the parent, we can only use …

fix(styles): Color-contrast on post-tabs with dark background

---

.changeset/purple-clocks-call.md
packages/internet-header/src/styles.scss
packages/styles/src/variables/_type.scss

The list is based on:
- https://phabricator.wikimedia.org/T175877
- https://github.com/twbs/bootstrap/pull/22377/files
Also I've tested "Segoe UI" with "Frutiger Neue For Post" and it works quite good as a fallback font without any changes: https://meowni.ca/font-style-matcher/

fix(styles, internet-header): Replaced system-ui fallback font with list of fonts

---

packages/documentation/.storybook/helpers/register-web-components.ts

This is a workaround for the following warning that appears when starting the dev server:
```
packages/documentation start: The above dynamic import cannot be analyzed by Vite.
packages/documentation start: See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ co
mment inside the import() call to suppress this warning.
packages/documentation start:
packages/documentation start:   Plugin: vite:import-analysis
packages/documentation start:   File: C:/work/design-system/packages/internet-header/dist/esm-es5/index-a2152ff5.js
```
This is the [linked issue on Stencil repository](https://github.com/ionic-team/stencil/issues/4122) which has not been …

chore(documentation): Workaround for vite:import-analysis in Internet-header with es5 build

---

.changeset/calm-spoons-bake.md
packages/components/cypress/e2e/tabs.cy.ts
packages/components/src/components/post-tab-header/post-tab-header.scss
packages/components/src/components/post-tab-header/post-tab-header.tsx
packages/components/src/components/post-tab-panel/post-tab-panel.tsx
packages/components/src/components/post-tabs/post-tabs.tsx
packages/documentation/src/stories/components/tabs/tabs.stories.ts

Workaround or alternative with light DOM (but not ready to use): https://github.com/swisspost/design-system/pull/2776

fix(components): Post-tabs cross-root aria-id

---

renovate.json

This package regularly causes the batch update to fail because of the deprecated Angular Demo App no longer able to build.

chore: exclude @types/node from batch update

---

packages/documentation/src/stories/components/blockquote/blockquote.docs.mdx
packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
packages/documentation/src/stories/utilities/spacing/spacing.docs.mdx

Not doing so, generates an error in the console (but it seems to work anyways).

fix(docs): use react syntax in mdx files

---

.changeset/sweet-spies-love.md
packages/internet-header/src/components/post-internet-breadcrumbs/post-internet-breadcrumbs.scss
packages/internet-header/src/components/post-internet-footer/post-internet-footer.scss
packages/internet-header/src/components/post-internet-header/post-internet-header.scss

If the Internet Header was used without having the styles as a global stylesheet, some CSS custom properties were not defined. This lead to focus rings not being visible. Extending the light theme colors for all the entry components defines these properties even if the styles package is not being used.

fix: define CSS custom properties for header/crumbs/footer

---

packages/demo/src/app/bootstrap/components/card/card-demo/card-demo.component.html
packages/demo/src/app/bootstrap/components/card/complex-card-demo/complex-card-demo.component.html
packages/demo/src/app/common/footer/footer.component.html
packages/demo/src/app/post-sample/components/topic-teaser/topic-teaser-demo/topic-teaser-demo.component.html
packages/demo/src/app/post-sample/components/topic-teaser/topic-teaser-right-demo/topic-teaser-right-demo.component.html
packages/documentation/.storybook/blocks/footer.tsx
packages/documentation/src/stories/components/topic-teaser/topic-teaser.stories.ts
packages/nextjs-integration/src/app/page.tsx

Example: https://sonarcloud.io/project/issues?open=AY3mTQCpUYAeUCKMCFbV&id=swisspost_common-web-frontend

fix(demo, documentation): Examples with images contains "image" keyword in alt

---

.changeset/fresh-bikes-rush.md
packages/components/cypress/e2e/tooltip.cy.ts
packages/components/cypress/fixtures/post-tooltip.test.html
packages/components/src/components/post-tooltip/post-tooltip.tsx

fix(components): post-tooltip doesn't show up when the pointer is on a child element

---

.changeset/config.json
.changeset/fifty-rabbits-flow.md

This will start to align the version of the fixed packages together. Fixed packages will be published under a new version, even if they did not have any changes (https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md).
There are several packages, that are not included in the list because they should still be versioned individually. The reason for this is, that they are not main deliverables of the Design System - styles and components. For example the documnetation, which can only be released with a version bump. If it would be fixed with the other packages, a correction of a typo would cause a version bump for all the deliverables, even if nothing changed for end users.

chore(versioning): fix versions of main packages

---

.changeset/light-pandas-wonder.md
CONTRIBUTING.md
packages/documentation/src/stories/components/forms/card-control/card-control.docs.mdx
packages/documentation/src/stories/components/rating/post-rating.docs.mdx
packages/documentation/src/stories/components/tag/tag.docs.mdx

We removed all LinkTo element in https://github.com/swisspost/design-system/issues/2464

fix(docs): Missing LinkTo element on rating component and remove all remaining LinkTo element

---

.changeset/witty-beans-dream.md
packages/documentation/src/stories/getting-started/introduction.docs.mdx

`rowspan=0`according to [mdn allows to span over an infinite number of row](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#rowspan). But it's actually not supported on Safari: https://caniuse.com/mdn-html_elements_td_rowspan_rowspan_zero

fix(docs): Rowspan 0 is not supported on Safari

---

packages/components/package.json
packages/components/stencil.config.ts
packages/documentation/.storybook/helpers/register-web-components.ts
packages/internet-header/stencil.config.ts

Sadly, I was not able to find a fix for our development problem, regarding stencil output and vite dynamic import.
But this changes should at least fix the component implementation in storybook and revert the unnecessary "empty" flags in the stencil configs.

fix: stencil config and component implementation in storybook

---

packages/documentation/.storybook/blocks/footer.tsx

docs: farewell Loïc

---

packages/intranet-header-workspace/projects/intranet-header-showcase/package.json

This should fix the broken release workflow on main.

chore: add package.json infos for intranet showcase

---

.github/workflows/deploy-demo.yaml
.github/workflows/deploy-documentation.yaml

Sadly the before made change would only work if we would change the site names in the netlify configuration.
Since I'm not sure what would happen, if I do that, I'm reverting the made changes with this PR.

fix(workflow): revert netlify_site_url

---

.changeset/brave-files-judge.md
packages/internet-header/src/components/post-klp-login-widget/post-klp-login-widget.scss
packages/internet-header/src/components/post-klp-login-widget/widget-styles.scss

fix(internet-header): show user info overflow

---

.changeset/pretty-bugs-change.md
packages/styles/src/components/stepper.scss
packages/styles/src/mixins/_utilities.scss
packages/styles/src/variables/components/_stepper.scss

I updated the styles quite drastically so that the stepper is CSS only and doesn't require the ngb progress bar to work.
I also used multiple CSS tricks to accommodate the current markup and avoid a major change, the code could be further simplified for the v8.

chore(styles): update horizontal stepper styles

---

.changeset/thirty-lemons-remember.md
packages/components-angular/projects/components/package.json
pnpm-lock.yaml

Installing @swisspost/design-system-components as a direct dependency in all the consumer projects, should not be necessary anymore.

fix(components-angular): add components package as peer dependency in components-angular package

---

.vscode/settings.json

This will pull custom rules and ignored paths and other settings from sonar cloud to the vs code extension.

chore: add sonarlint mapping for vscode

---

.changeset/proud-spies-tap.md
packages/styles/gulpfile.js

This will allow projects not using Sass to import individual component styles.

feat(styles): build individual components

---

.github/actions/deploy-to-netlify/action.yaml
.github/workflows/deploy-demo.yaml
.github/workflows/release-demo.yaml

Deployments of Angular SPAs are not working correctly with netlify-cli@17.
Downgrading to v16 seems to work.

chore(workflows): downgrade netlify-cli to v16 for demo app deployments

---

.changeset/lovely-dancers-tap.md
packages/components/.eslintrc.js
packages/components/.gitignore
packages/components/package.json
packages/components/stencil.config.ts
packages/documentation/src/stories/getting-started/packages/components/components-cdn-lazy-loaded-specific.sample.html
packages/documentation/src/stories/getting-started/packages/components/components-js-specific.sample.js

In the end this task does not solve any bug with importing web components individually, it is just a nice-to-have simplification.

chore(components): update the component's package output target

---

packages/documentation/vite.config.js
packages/styles/gulpfile.js

This change excludes `@swisspost/design-system-styles` from the vite optmizeDeps workflow for the documentation package. This seems to get rid of some of the "can't import dynamic dependency" issues.
Reloading after a style change is still pretty slow, but also a lot of unnecessry recompiles are happening. The potential for improvement is quite big here.

chore: fix pnpm start command

---

.github/workflows/unit-tests.yaml
packages/styles/gulpfile.js

This PR is copying temporary token files before running the tests. This should fix the failing unit test runs.

chore: fix gulp sass tests

---

.github/actions/setup-netlify-cli/action.yaml

Our last successful deploys were on the 20th of September. On that day, netlify released a patch update that seems to have broken the deploy command if netlify builds are disabled (https://github.com/netlify/cli/blob/main/CHANGELOG.md#17362-2024-09-20). Trying to fix the issue by setting netlify version to a version before that.
Submited an issue for netlify cli: https://github.com/netlify/cli/issues/6841

chore: set a fixed netlify cli version

---

.github/CODEOWNERS

Adding members as codeowners of everything conflicts a bit with the rule of 1 review necessary for merging a PR (it's not possible to specify which team needs to review before a merge can happen). Having the members reviewing documentation updates as well should already be an improvement.

chore: add members as codeowners of the docs

---

renovate.json

Renovate, in it's current config, is updating all minor and patch updates in one group. This gets a little overwhelming at times. This PR creates some more groups for the most important dependencies so that they can be tackled one after the other.

chore: separate important packages from group update

---

.changeset/lovely-mirrors-travel.md
packages/styles/src/post-tokens-external.scss
packages/styles/src/post-tokens-internal.scss

Wrapping tokens into a layer allows consuming projects to easily define the cascade order of the tokens, no matter at what position they get imported.

chore: use layers for token entry files

---

.changeset/shaggy-experts-give.md
packages/components-react/package.json

This PR sets the react components package to public, which will release it to npm under the version 9.0.0-next.X.

chore: release react components

---

packages/changelog-github/package.json
packages/components-angular/projects/components/package.json
packages/icons/package.json
packages/intranet-header-workspace/projects/intranet-header/package.json
packages/styles/package.json
packages/tokens/package.json

This sets the homepage field in the package.json of some packages to our actual, nice URL.

chore: fix homepage link

---

packages/styles/CONTRIBUTING.md

As resolved to in a meeting on the 14th of October 2024, margins for basic elements should be defined and reset for first- and last child respectively.

chore: document margins decision

---

.github/workflows/fetch-icons.yaml

When building the styles, it's dependencies need to be built first (currently the tokens).

chore: fix icons workflow

---

packages/components/cypress/support/commands.ts
packages/components/stencil.config.ts
packages/documentation/cypress/snapshots/components/accordion.snapshot.ts
packages/documentation/cypress/snapshots/components/card-control.snapshot.ts
packages/documentation/cypress/snapshots/components/collapsible.snapshot.ts
packages/documentation/cypress/snapshots/components/logo.snapshot.ts
packages/documentation/cypress/snapshots/components/tabs.snapshot.ts
packages/documentation/src/stories/components/forms/card-control/web-component/card-control.stories.ts
packages/documentation/src/stories/components/forms/card-control/web-component/card-control.styles.scss
packages/documentation/src/stories/components/popover/popover.stories.ts
packages/documentation/src/stories/components/tooltip/tooltip.stories.ts
pnpm-lock.yaml

This changes how the hydrated flag is add to a web-component.
The class `hydrated` is no longer important/used and therefore also not causing the component to show up, when added statically or just before the component has been hydrated.
Developers which copied the components dom strucure from the code panel of our docs pages (for example for the components `tooltip` and `placeholder`) should remove the class `hydrated` out of there HTML, even though it's not mandatory, because the class will just not have any impact anymore.
On the other hand, if the class was used in some e2e tests of the project, it may be necessary to update those.

fix(components): switch stencil hydrated flag from `class` to `attribute`

---

.changeset/tiny-socks-count.md
packages/components/src/components/post-accordion-item/post-accordion-item.tsx
packages/components/src/components/post-accordion/post-accordion.tsx
packages/components/src/components/post-alert/post-alert.tsx
packages/components/src/components/post-icon/post-icon.tsx
packages/components/src/components/post-logo/post-logo.tsx

Delays the prop checks until the last lifecycle hook to give frameworks time to render their props before the check runs.

fix: check props on componentDidLoad

---

packages/components/src/components/post-popovercontainer/post-popovercontainer.tsx

This feature allows to specify how much space the floating-ui library should account for when positioning overlays near the edge of the page. Set to 0 if popovers should be allowed to touch the edge of the window.
No changeset because this component is not documented.
This is needed for the megadropdown in the header component.

feat(components): add edge gap property to popovercontainer

---

packages/tokens/package.json
pnpm-lock.yaml

This is required for the publish command to work properly because only files in dist are included in the package.

chore: copy files on tokens build

---

.changeset/chilly-seals-serve.md
packages/components/src/components/post-tooltip/post-tooltip.tsx

Pointer events is not set to none on the host and button is clickable after the tooltip disappears so this bit of code does not seem useful.

fix(components): error in console on tooltip exit

---

.github/workflows/create-token-pr.yaml

The issue seem to be linked to the token used by the workflow: https://github.com/orgs/community/discussions/37103.
`actions/checkout` sets up the repository so it always uses the GITHUB_TOKEN which never triggers subsequent workflows.

chore: update tokens workflow

---

.changeset/brave-beds-punch.md
packages/demo/src/app/intranet-layout/intranet-layout.component.html
packages/documentation/src/stories/components/intranet-header/intranet-header.stories.ts
packages/intranet-header-workspace/projects/intranet-header/src/lib/swisspost-intranet-header.component.ts
pnpm-lock.yaml

! The required input value has recently changed !
Due to the technical conversion of the intranet backend from Sitecore to Sharepoint, the value required for the property to display a user image has changed. Previously the user ID was required, now this property expects the user-specific e-mail address.

fix(intranet-header): update avatar url, used to load a users profile picture form the intranet backend

---

packages/styles/src/components/button.scss

The `.btn-link` currently has an inline padding when used in combination with an `.btn-sm` or `.btn-lg` class.

fix(styles): remove button link padding

---

packages/components/src/components/post-header/post-header.tsx
packages/documentation/src/stories/components/header/components/header.markup.ts

This navigation will not be needed for cargo and is currently undergoing a redesign. Therefore it will not be part of the first implementation of the header.

docs: remove audience navigation

---

.github/workflows/release-documentation.yaml
.github/workflows/release.yaml

The netlify cli command `netlify deploy` lets you decide if you want to build your package before deployment before the deployment happens or not.
Until now, we had to add `--build false` to this command to omit the build step (because we had either a prebuilt artefact or we had specific build steps in our workflows before the deployment steps anyway.
Since a week or so, this behavior changed in the netlify cli (without any update from our side).
See the "Publish documentation to netlify" step in the "Release Documentation" workflow of yesterdays release: https://github.com/swisspost/design-system/actions/runs/12745852862/job/35520700904
This also resulted in a failure in all of our preview deployment workflows, because there, we do not install node_modules before starting the deployment, …

fix: netlify deploy command

---

.changeset/purple-apes-happen.md
packages/styles/src/components/stepper.scss

…r-link to stepper-link:before

fix(component): fix an issue where the Stepper started with step 0 on small screen sizes

---

.changeset/eighty-ghosts-explain.md
packages/components/src/components/post-popovercontainer/post-popovercontainer.scss

chore(component): add shadow on optional arrow for `post-tooltip` component (cherry pick #4441 to v8)

---

.npmrc
package.json

Regarding the [docs](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions) this should be enough to publish packages with provenance.
But it could also be a configuration problem in the SWISSPOSTDEVS_ACCESS_TOKEN, which is used to call the changesets/action in our release workflow.
@gfellerph Let's try this first, before we switch to the GITHUB_TOKEN.
In case this will not work as well, I'll remove the provenance settings for the moment, so the release is not blocked anymore.

fix: release workflow publish with provenance

---

.github/workflows/sonar-analysis.yaml

The problem: 
After the solution implemented by this PR, both warnings are not present anymore:

fix(workflow): replace deprecated sonarcloud-action with sonarqube-scan-action

---

packages/documentation/netlify.config.json

Since netlify unblocked our next url again, we can revert the netlify.config.json back to what we had before we switched to the temp url.

revert: reset the netlify config to point to the next netlify page again

---

packages/documentation/src/stories/modules/header/header.styles.scss

Improves overflow container styling on the header docs. The header no longer scrolls out of view unexpectedly.

fix: header overflow container styles

---

.changeset/chilled-crabs-march.md
.changeset/thin-monkeys-chew.md
packages/documentation/src/stories/misc/migration-guide/migrationv8-9.component.ts
packages/styles/src/components/form-input.scss
packages/styles/src/components/form-textarea.scss
packages/styles/src/components/timepicker.scss
packages/styles/src/mixins/_forms.scss
packages/styles/tests/mixins/forms.test.scss
packages/styles/tests/mixins/index.test.scss

There was an invalid `::input-placeholder` on the placeholder mixin which I removed. The remaining `::placeholder` seemed sufficent as it is widely available. Therefore the `@mixin placeholder()` did not seem relevant anymore as it only contained the `::placeholder` CSS selector so I removed it as well.

fix(styles): remove placeholder mixin

---

.changeset/friendly-singers-wave.md
packages/components/cypress/e2e/popover.cy.ts
packages/components/src/components/post-popover/post-popover.tsx

Changed the globalToggleHandler method of the post-popover component. Before it only checked if the event target had the 'data-popover-target' attribute. When for example an icon is nested in the trigger, this would result to false and the popover would not open. In the new implementation instead of just checking the e.target we traverse the DOM tree upwards searching for an element with the 'data-popover-target' attribute. Now clicking on an icon nested in the popover trigger, the popover will be opened/closed as expected.
https://github.com/user-attachments/assets/6519dcde-f1d2-4354-a324-6f9c2609f7bd
---
- ⚠️ My changes …

chore(components): fixed popover not opening when clicking on elements nested in trigger (v8)

---

.changeset/lazy-tables-agree.md
packages/components/cypress/e2e/popover.cy.ts
packages/components/src/components/post-popover/post-popover.tsx

Changed the globalToggleHandler method of the `post-popover` component. Before it only checked if the event target had the 'data-popover-target' attribute. When for example an icon is nested in the trigger, this would result to false and the popover would not open. In the new implementation instead of just checking the e.target we traverse the DOM tree upwards searching for an element with the 'data-popover-target' attribute. Now clicking on an icon nested in the popover trigger, the popover will be opened/closed as expected.
https://github.com/user-attachments/assets/e5448e03-75c9-42cb-af49-fe726b4f1e44
---
- ⚠️ My changes …

chore(components): fixed popover not opening when clicking on elemets nested in trigger (v9)

---

.changeset/popular-otters-rhyme.md
packages/documentation/src/stories/components/stepper/stepper.docs.mdx
packages/documentation/src/stories/components/stepper/stepper.stories.ts
packages/styles/src/components/stepper.scss

Cherry pick stepper fix on firefox to v7

fix(documentation): stepper progress on firefox

---

.github/workflows/fetch-icons.yaml

This PR replaces the compromised tj-actions/changed-files by its uncompromised equivalent provided by step-security in the icon workflow.
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
---

chore: replace tj-actions/changed-files by step-security/changed-files

---

.changeset/wicked-students-cough.md
packages/components/src/components/post-language-option/post-language-option.tsx
packages/components/src/components/post-menu/post-menu.tsx

Resolved accessibility violations in the `post-language-switch` component by adding the role="menu" to the `post-menu` component.

fix(component): resolve accessibility violations in the `post-language-switch` component

---

.changeset/warm-seals-glow.md
packages/tokens/tokensstudio-generated/tokens.json

This cleans up a remaining definition for Frutiger in the tokens file. The definition was not used.
---

fix: patch font tokens

---

.devcontainer/devcontainer.json
package.json
packages/internet-header/package.json
pnpm-lock.yaml

Fix styles version for outdated v6 so the internet-header package only gets updates from the current version.
---

fix: stop internet header from updating through v6 releases

---

.changeset/strange-seas-drop.md
packages/components/cypress.config.js
packages/components/cypress/e2e/icon.cy.ts
packages/components/src/components/post-icon/post-icon.tsx

Updated the fallback CDN URL in the `post-icon` component for release/v8 branch.
---

fix(post-icon): add package version in CDN fallback URL for v8

---

.changeset/empty-crabs-work.md
packages/components/src/components/post-header/post-header.tsx

Fixes the version attribute to `data-version` on the `post-header` component
---

fix(components): fix post-header version attribute

---

packages/documentation/src/stories/foundations/icons/icon.stories.ts

fix(documentation): fix import of PostIcon type in icon stories

---

.github/actions/artifact-download/action.yaml
.github/actions/artifact-upload/action.yaml
.github/actions/preview/message/create/action.yaml
.github/actions/preview/message/update/action.yaml
.github/actions/setup-pnpm/action.yaml
.github/workflows/build-demo.yaml
.github/workflows/build-documentation.yaml
.github/workflows/build-tokens.yaml
.github/workflows/deploy-demo.yaml
.github/workflows/deploy-documentation.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/fetch-icons.yaml
.github/workflows/lint.yaml
.github/workflows/pr-title-lint.yaml
.github/workflows/release-demo.yaml
.github/workflows/release-documentation.yaml
.github/workflows/release.yaml
.github/workflows/snapshot-tests.yaml
.github/workflows/sonar-analysis.yaml
.github/workflows/stale.yaml
.github/workflows/unit-tests.yaml

This PR updates all GitHub Actions references in workflows and custom actions to use commit hashes instead of version tags for release/v7. It also addresses replacing the deprecated sonarcloud-action with sonarqube-scan-action for Sonar workflow.
Changes
1. Replaced version tags (e.g., @v4, @v7) with specific commit hashes in multiple workflows and action files.
2. Ensured that actions/checkout, actions/upload-artifact, actions/github-script, and other third-party actions reference their exact commit SHA.
3. Replaced deprecated sonarcloud-action with sonarqube-scan-action.
With the PR I have replaced deprecated sonarcloud-action with sonarqube-scan-action to address the warning
--- …

chore(workflow): reference GitHub Actions by hash instead of version (v7)

---

.github/actions/artifact-download/action.yaml
.github/actions/artifact-upload/action.yaml
.github/actions/preview/message/create/action.yaml
.github/actions/preview/message/update/action.yaml
.github/actions/setup-pnpm/action.yaml
.github/workflows/build-demo.yaml
.github/workflows/build-documentation.yaml
.github/workflows/build-tokens.yaml
.github/workflows/deploy-demo.yaml
.github/workflows/deploy-documentation.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/fetch-icons.yaml
.github/workflows/lint.yaml
.github/workflows/pr-title-lint.yaml
.github/workflows/release-demo.yaml
.github/workflows/release-documentation.yaml
.github/workflows/release.yaml
.github/workflows/snapshot-tests.yaml
.github/workflows/sonar-analysis.yaml
.github/workflows/stale.yaml
.github/workflows/unit-tests.yaml

This PR updates all GitHub Actions references in workflows and custom actions to use commit hashes instead of version tags for release/v8. It also addresses replacing the deprecated sonarcloud-action with sonarqube-scan-action for Sonar workflow.
Changes
1. Replaced version tags (e.g., @v4, @v7) with specific commit hashes in multiple workflows and action files.
2. Ensured that actions/checkout, actions/upload-artifact, actions/github-script, and other third-party actions reference their exact commit SHA.
3. Replaced deprecated sonarcloud-action with sonarqube-scan-action.
With the PR I have replaced deprecated sonarcloud-action with sonarqube-scan-action to address the warning
--- …

chore(workflow): reference GitHub Actions by hash instead of version (v8)

---

.changeset/hungry-ways-deliver.md
packages/components/src/components/post-linkarea/post-linkarea.scss
packages/components/src/components/post-linkarea/post-linkarea.tsx

Make post-linkarea a shadow component to avoid hydration errors.
---

feat(components): make post-linkarea a shadow component

---

.changeset/short-rockets-cry.md
packages/styles/src/templates/_not-defined.template.scss

SSR components, which are hydrated on the server already, will be visible from the very beginning (even before JS is ready), while client side components will only become visible, as soon as they have been hydrated by JS on the client.
---

fix(styles): update the not-defined selector to render ssr components already before js is enabled

---

renovate.json

As the system dependencies grow, it becomes less and less likely, that a grouped minor and patch update PR can be merged without issues. This change would only group patch updates into one PR and submit minor updates individually, keeping the existing exclusion rules in place.
It also updates the label assigned to renovate PRs to not mess with our package labels.

chore: group only patch updates

---

.changeset/lazy-eels-nail.md
packages/documentation/src/stories/components/toast/toast.stories.ts

Fixed an issue where the close button in the Toast component was not properly aligned when the toast was rendered with `position: fixed`.
**Before:**
**After:**
---

fix(docs): align close button correctly when toast is fixed positioned

---

.changeset/nice-dogs-kick.md
packages/styles/src/utilities/_variables.scss

Added back the `.text-reset` class as it was deleted accidentally.

fix(styles): add back `text-reset` class

---

.changeset/gentle-pots-kick.md
packages/documentation/.storybook/styles/preview.scss
packages/documentation/src/stories/components/avatar/avatar.docs.mdx
packages/documentation/src/stories/components/avatar/avatar.sample.scss

Updated colors of some of the text elements in the `pre` parts of the docs.
Changed the avatar SCSS code preview to use `Source` in order to have a dark background like the rest of the docs.

fix(documentation): improve contrast on <pre> code

---

.changeset/chatty-rivers-drum.md
packages/documentation/src/stories/utilities/vertical-align/vertical-align.styles.scss

Changed a text's color in the Vertical align documentation to improve contrast and make it accessible.

fix(documentation): improve contrast to vertical align preview

---

.changeset/chatty-knives-grab.md
packages/components/src/components/post-tooltip/post-tooltip.tsx

When delay is used on the `<post-tooltip>` component, an error sometimes occur when cursor leaves the trigger to go to the tooltip itself. It calls the `show` method but the host is undefined.

fix(components): error on post-tooltip when show is called on delay

---

.changeset/two-planets-fix.md
packages/documentation/src/stories/modules/footer/footer.docs.mdx

This PR adds the missing Figma design link to the Composable Footer documentation page in Storybook.

chore(docs): add missing Figma link to Composable Footer documentation

---

.changeset/two-pigs-tap.md
packages/documentation/public/_redirects
packages/documentation/public/assets/versions.json

This PR updates all v5 documentation links:
- Changed from: `https://6401b58ebf0f4e298ee2dbe7--swisspost-web-frontend.netlify.app` 
- Changed to: `https://swiss-post-design-system-v5.netlify.app`
Reference to the ticket: https://github.com/orgs/swisspost/projects/3/views/11?pane=issue&itemId=107557929&issue=swisspost%7Cdesign-system%7C5334

fix(docs): fix broken links to v5 documentation throughout the codebase/v8

---

.changeset/young-mangos-jump.md
packages/documentation/public/_redirects
packages/documentation/public/assets/versions.json

This PR updates all v5 documentation links:
Changed from: https://6401b58ebf0f4e298ee2dbe7--swisspost-web-frontend.netlify.app
Changed to: https://swiss-post-design-system-v5.netlify.app

fix(docs): fix broken links to v5 documentation throughout the codebase/v9

---

.github/workflows/release.yaml

Currently, whenever a major change is merged into the `main` branch, a new release branch is created.
However, `main` is only used for pre-releases, so it should not create release branches.
Changeset is correctly handing this, marking the change as major but not increasing the major version number.
We just need to check this number to know if we are releasing or pre-releasing.
---

chore: prevent release workflow from creating release branches for the next version

---

package.json
packages/nextjs-integration/package.json

- Added `typecheck` script to nextjs-integration package.json
- Modified `build` script to run type checking before building (`pnpm run typecheck && pnpm clean && next build`)
- Added `nextjs:typecheck` script to root package.json for convenience

feat(packages): add TypeScript type checking to build process into the nextjs-integration package

---

packages/components-angular/package.json
packages/components-angular/projects/components/package.json
packages/components-react/package.json
packages/components/package.json
packages/documentation/package.json
packages/icons/package.json
packages/internet-header/package.json
packages/nextjs-integration/package.json
packages/styles-primeng-workspace/package.json
packages/styles-primeng-workspace/projects/styles-primeng/package.json
packages/styles/package.json
packages/tokens/package.json
pnpm-lock.yaml

This moves main to the next major version, since we're introducing an in-between version compatible with Angular 19. Fingers crossed. This change has been made manually. Tasks to look at are added to https://github.com/swisspost/design-system/issues/4565.

chore: move main (next) to v10

---

.github/workflows/scripts/icons.mjs

The serial comma was not correct when 2 icons were changed.
---

chore: modify icon workflow to not use serial comma

---

.changeset/shaggy-women-drive.md
packages/documentation/src/stories/components/textarea/textarea.snapshot.stories.ts
packages/styles/src/components/form-textarea.scss

Fixed disabled textarea labels to inherit parent background color using `--post-current-palette-bg` variable.
Before:
After:

fix(styles): fix background on disabled textarea labels to maintain readability when content overflows

---

.github/workflows/scripts/icons.mjs
packages/icons/CHANGELOG.md

The icons change log was missing a line break and the icon names were upper-cased while they are lower-cased in the documentation. Update it to fix these issue and updated the workflow to no longer have them in the future.
---

chore(icons): update broken change log

---

.changeset/funny-glasses-train.md
packages/styles/src/components/form-textarea.scss

This PR fixes issue where disabled textareas are not scrollable in Chrome. 
The fix adds `pointer-events: all` to disabled textareas to ensure users can still scroll 
through content even when the textarea is disabled.

fix(styles): restored scroll functionality on disabled textareas

---

.changeset/angry-trams-stick.md
packages/components/src/components/post-tooltip/post-tooltip.scss

- Updated `max-width` from 200px to 280px for better content accommodation
- Implemented proper word breaking for content that exceeds container width
---

fix(styles): fixed `post-tooltip` text overflow by implementing proper word wrapping and updating width constraints

---

packages/documentation/netlify.config.json

Re-routes v8 deploys to the dedicated v8 netlify site.

chore: fix v8 deploy target

---

.changeset/tricky-buckets-sniff.md
packages/components/src/animations/collapse.ts
packages/components/src/components/post-collapsible/post-collapsible.tsx

This PR adds visibility check before committing animation styles in PostCollapsible.toggle() to prevent InvalidStateError when the target element is hidden. This resolves errors occurring when animating elements inside hidden tab panels.
---
---------
---
- ✅ My code follows the style guidelines of this …

fix(component): fix animation error in `post-collapsible` rendered in hidden tabs (cherrypick/v9)

---

.changeset/angry-trams-stick.md
packages/components/src/components/post-tooltip/post-tooltip.scss

Cherrypick of the  https://github.com/swisspost/design-system/pull/5544 to release/v9
- Updated `max-width` from 200px to 280px for better content accommodation
- Implemented proper word breaking for content that exceeds container width
---
---
- 🛠️ I …

fix(styles): fixed post-tooltip text overflow by implementing proper word wrapping and updating width constraints (cherrypick/v9)

---

package.json

Since we did not automate that already, we need to manually set the publish tag on older release branches to their version, so the package won't be released under the tag "main". Therefor this PR sets the tag to "version-8" for the current release branch.
---

chore: manually set the release tag of the changeset:publish script to "version-8"

---

.npmrc

Some Post projects require the internal Post registry to be set at the npm user config level.
Specifying the registry at project level prevent dependencies being installed for unwanted registries. 
---

chore: add a registry field to the .npmrc

---

.changeset/mean-oranges-smile.md
packages/styles/src/variables/components/_tag.scss

This reverts commit 79f93287684d83be51d8605f388f0167a89543ac.
After checking with the designers, we still do not know which colors the tag component will be offered in. 
Therefore, we should wait for a definite design before implementing breaking changes in this component.
---

chore(styles): revert update colors list for `tag` component (#5476)

---

.changeset/odd-parrots-press.md
packages/components/cypress/e2e/footer.cy.ts
packages/components/src/components/post-accordion/readme.md
packages/components/src/components/post-footer/post-footer.tsx
packages/components/src/components/post-footer/readme.md

Took the typo fix from @schaertim's PR #5709 to separate it from the tests.

fix(components): typo for `post-accordion` in `post-footer`

---

.changeset/real-steaks-clap.md
packages/components/cypress/e2e/accordion.cy.ts
packages/components/src/components/post-accordion-item/post-accordion-item.tsx

- Fixed event guard configuration to properly handle accordion item toggle events
- Corrected targetLocalName from `post-collapsible` to `post-accordion-item` in event listener
- Chevrons now correctly rotate when accordion items are expanded/collapsed
- Added comprehensive test coverage for icon rotation behavior across different accordion states
- Research revealed regression was caused by the eventGuard implementation PR
---
- 🧪 I have added tests that prove my fix is effective or that my feature …

fix(component): fix the `post-accordion-item` chevron no longer rotating

---

.github/ISSUE_TEMPLATE/component_tokens.md

This PR adds a label to the tokens ticket so that they do not appear as ready for triage until the component design is defined.
---

chore: add "on hold" label to the token ticket template

---

.changeset/forty-rings-refuse.md
packages/documentation/src/stories/packages/styles-primeng/styles-primeng.docs.mdx

**Changes**
- Added `PostBanner` component with clear messaging about package limitations
- Emphasized that only DataTable components are styled by this package
- Clarified that other PrimeNG components will use default PrimeNG appearance
---

chore(docs): clarify PrimeNG package scope

---

.changeset/beige-fans-see.md
packages/components/src/components/post-popover/post-popover.scss
packages/components/src/components/post-tooltip/post-tooltip.scss
packages/documentation/src/stories/components/popover/popover.stories.ts
packages/documentation/src/stories/components/tooltip/tooltip.stories.ts

This PR updates the `tooltip` and `popover` as follows:
1. Adds the `.palette` class in both components' examples in the documentation.
2. Updates both components styles to override the default popovercontainer component styles.

chore(components): update tooltip and popover styles for palettes 2.0

---

.changeset/yummy-dots-look.md
packages/documentation/src/stories/foundations/icons/search/search-icons.blocks.tsx

Hides the scroll-to anchor on the icons search page for keyboards and also from screenreaders.
---

fix(docs): hide scroll-to anchor on icons search page

---

.changeset/unlucky-ravens-sort.md
packages/components/cypress/e2e/tooltip.cy.ts
packages/components/src/components/post-tooltip-trigger/post-tooltip-trigger.tsx

This PR updates the `post-tooltip-trigger` to not throw an error if it does not contain an internal HTML element.

chore(components): prevent errors when post-tooltip has no internal element (cherrypick /v9)

---

packages/components-angular/projects/consumer-app/src/app/routes/home/home.component.html

Quick fix in the `components-angular` playground example where the `post-tooltip-trigger` was linked to a non-existing `post-tooltip`.

chore(components-angular): fix the visual example of the `post-tooltip` in angular playground

---

.changeset/flat-turtles-show.md
packages/components/src/components.d.ts
packages/components/src/components/post-header/post-header.scss

This PR fixes the header overlapping content issue on tablet and mobile devices reported in issue #5820 by reverting the changes introduced in PR #5621.
- **Reverted** the changes from PR #5621 
**Note:** A separate ticket has been created to address the original iOS Chrome gap issue with an alternative approach:
https://github.com/orgs/swisspost/projects/3/views/12?pane=issue&itemId=120735062&issue=swisspost%7Cdesign-system%7C5825
---

fix(component): fix `<post-header>` component overlapping content on tablet and mobile devices

---

.changeset/selfish-donuts-invite.md
packages/components/src/components/post-tooltip/post-tooltip.scss

This PR updates the tooltip `display` property to `contents` to avoid affecting the layout.

chore(components): update tooltip display to `contents`

---

.changeset/early-hats-do.md
packages/documentation/public/assets/versions.json

Removed the bootstrap and ng-bootstrap dependencies from the versions.json file to update the VersionSwitcher.

chore(docs): remove bootstrap and ng-bootstrap dependencies from versions.json

---

.changeset/two-hounds-march.md
packages/styles/src/components/tables.scss

This change makes the table component a bit more independent for projects that are not using our reset file. The caption-side is already defined there for the element table selector, but not all projects are using our reset.

fix: define caption side for tables

---

packages/nextjs-integration/src/app/page.tsx

After the removal of the `<post-tag>` component in #5764, we need to clean up the Next.js integration package where `PostTag` is still being imported but no longer available.
The error occurs when running the Next.js dev server:
`Attempted import error: 'PostTag' is not exported from '@swisspost/design-system-components-react/server' (imported as 'PostTag').`
---

chore(components): remove `PostTag` from Next.js integration package

---

.github/workflows/e2e-tests.yaml

The `pnpm bootstrap` command is optimised to only run only necessary pacakges for development, we should do a full build for e2e tests here to catch any issues in building integration packages as well. Otherwise, issues in these packages are going unnoticed.

test: run full build for e2e tests

---

package.json
packages/documentation/.storybook/components/docs/header.tsx
packages/documentation/.storybook/components/docs/layout.scss
pnpm-lock.yaml

Added a EOL banner on v5's design system documentation

chore(docs): add EOL banner

---

.changeset/fine-berries-burn.md
packages/documentation/src/stories/components/dialog/dialog.stories.ts

Removed the nested `h2` heading markup within the dialog header.

fix(docs): removed nested heading markup in dialog header

---

.changeset/empty-pants-brake.md
packages/documentation/.storybook/helpers/open-full-screen-demo.ts

The "Copy deep link" button now copies the full URL, including `https://`.
---

fix(docs): improve the copy deep link functionality

---

.changeset/spicy-radios-behave.md
packages/components/eslint.config.js
packages/components/src/components.d.ts
packages/components/src/components/post-banner/post-banner.tsx
packages/components/src/components/post-closebutton/post-closebutton.tsx
packages/components/src/components/post-closebutton/readme.md
packages/components/src/utils/event-from.ts

Remove the `postCLick` event since we con simply use `click`.
This event is not yet released this I simply updated the related changeset file.
---

chore(component): remove unnecessary event in the post-closebutton

---

packages/documentation/src/stories/misc/migration-guide/migrationv9-10.component.ts
packages/eslint/docs/rules/html/migrations/no-deprecated-loader.md
packages/eslint/src/rules/html/migrations/index.ts
packages/eslint/src/rules/html/migrations/no-deprecated-loader.ts
packages/eslint/test/rules/html/migrations/no-deprecated-loader.spec.ts

ESLint rule to update the `.loader-xs` and `.loader-sm` classes to `.loader-16` and `.loader-40` respectively.
---

feat(eslint): add rule to update deprecated loader classes

---

.github/workflows/release.yaml

The workflow has been listed as a trusted publisher therefore the npm token is no longer necessary.
---

chore: remove npm token from the release workflow

---

.changeset/giant-poets-exist.md
packages/components/src/components/post-accordion-item/post-accordion-item.tsx
packages/components/src/components/post-accordion-item/readme.md

This PR adds a "button" part for the accordion items header button, as already implemented in our "next" version.

feat(components): add part `button` in the `post-accordion-item` component

---

.changeset/flat-moments-sit.md
packages/styles/src/mixins/_notification.scss
packages/styles/src/variables/components/_notification.scss

Replace 4-digit Post Icons with their corresponding signal icon equivalents in toast notifications to improve status/feedback communication.
---

chore(styles): replace `Post Icons` with `signal icons` in `toast` component
