- packages/web-styles-migrations/package.json
- pnpm-lock.yaml
Copy package.json to dist and erase publishConfig.directory to be able to publish to npm.
> build(web-styles-migrations): copy package.json on build

- packages/web-styles/src/themes/bootstrap/_overrides-features.scss
This variable was deleted by mistake!
> fix(boostrap): reintegrate bootstrap variable "$variable-prefix"

- .changeset/sweet-poets-know.md
- packages/web-styles/src/components/form-select.scss
This bug was reportet for Firefox only
> fix(form-select): Adds text color when focussed in hcm

- README.md
🎨 by Larissa Sequeira
Co-authored-by: Larissa Sequeira <81462538+LarissaMS@users.noreply.github.com>
> chore(readme): add splash screen

- .github/workflows/build.yaml
Only build the demo app and deploy it, if the given paths changed (or not if negated)
> feat(build): add path filters to the build workflow

- packages/styles/package.json
This will improve the speed of the JEST test script and thus speed up the test workflow on Github.
> test(styles): add only-changed flag to jest test script

- packages/demo/src/app/common/footer/footer.component.ts
- packages/demo/src/app/home/home.component.html
- packages/demo/src/app/home/home.component.scss
**Switches:**
Based on feedback from the community, the switches were not the ideal way for filtering the migration instructions.
**Suporters update:**
While @Janobob made valuable contributions to the project, he should no longer be contacted for support directly.
> chore(demo): update start page

- .changeset/nervous-dodos-own.md
- packages/demo/src/app/home/home.component.html
- packages/demo/src/app/home/home.component.ts
…from bootstrap alert component
> docs(styles-migration): remove alert-fixed-bottom class requirement from boostrap alert component

- .changeset/eighty-news-play.md
- packages/documentation/.storybook/main.js
- packages/documentation/package.json
- pnpm-lock.yaml
Added the storybook accessibility plugin which shows an Accessibility tab with various, non-conclusive tests
> feat(docs): add accessibility plugin

- .changeset/good-pets-think.md
- .github/workflows/deploy-documentation.yaml
- .github/workflows/release-documentation.yaml
- README.md
- packages/components/README.md
- packages/demo/src/app/app.component.html
- packages/documentation/README.md
- packages/internet-header/readme.md
Switched from styles.design-system to next.design-system.post.ch for better naming of the beta docs.
> fix: deploy to next.design-system.post.ch

- .changeset/healthy-impalas-tease.md
- packages/components-angular/projects/intranet-header/src/lib/swisspost-intranet-header.component.ts
Updated the type for prop currentUserId to string
> fix(intranet-header): update currentUserID typing

- .changeset/rare-years-sell.md
- packages/internet-header/src/index.html
- packages/internet-header/src/services/config.service.spec.ts
- packages/internet-header/src/services/config.service.ts
Fixed environment string comparison when upper case characters are used to define the environment property
> fix(header): convert env to lowercase for comparison

- packages/icons/jest.config.js
- packages/icons/package.json
- packages/icons/src/utilities/environment.ts
- packages/icons/tests/setup-env.js
- pnpm-lock.yaml
Informs the user about missing environment variables.
> fix(icons): throw error when env vars are undefined

- .changeset/few-moons-train.md
- packages/internet-header/package.json
- packages/internet-header/src/services/search/places.service.ts
- packages/internet-header/src/services/search/search-utilities.ts
- pnpm-lock.yaml
It's no longer necessary to create a slug for places.post.ch detail pages.
> fix: remove slugify

- .changeset/lucky-frogs-wonder.md
- packages/styles/src/components/alert.scss
- packages/styles/src/components/toast.scss
- packages/styles/src/components/utilities.scss
- packages/styles/src/functions/_color.scss
- packages/styles/src/functions/_contrast.scss
- packages/styles/src/functions/_index.scss
- packages/styles/src/mixins/_button.scss
- packages/styles/src/placeholders/_notifications.scss
- packages/styles/src/variables/_color.scss
Using a new algorithm to calculate color contrast as the old one did not satisfy WCAG 2.1 AA in all cases (success button). The new check is based on this blogpost https://codetuts.dev/text-contrast-sass/ with adaptions for modern sass syntax and our needs.
> fix(styles): update contrast function

- packages/demo/src/app/ng-bootstrap/components/tooltip/tooltip-demo/tooltip-demo.component.html
Somehow the inline position of the buttons caused layout instability on hover. Fixed it with flex.
> docs: wrap buttons for stability

- .changeset/light-plums-juggle.md
- packages/styles/src/themes/bootstrap/_overrides-color.scss
- packages/styles/src/variables/_color.scss
- packages/styles/src/variables/components/_alert.scss
- packages/styles/src/variables/components/_button.scss
Changed the info color to light blue for alerts, notifications and contextual usage
> fix(color): update info color to light blue

- .changeset/kind-forks-hammer.md
- package.json
- packages/components-react/package.json
- packages/components/src/components/post-collapsible/post-collapsible.tsx
- packages/components/src/components/post-icon/post-icon.tsx
- packages/documentation/src/stories/misc/versions.components.tsx
- packages/documentation/src/stories/misc/versions.stories.mdx
- pnpm-lock.yaml
Added a story showing all interesting dependency version numbers used for this particular build of the documentation.
> feat(docs): add versions story

- .changeset/silent-mails-sleep.md
- packages/internet-header/src/components/post-search/post-search.tsx
NVDA output:
```
Meist gesuchte Services list with 7 items Paketetiketten erstellen link
Post umleiten link
```
> feat(internet-header): add aria-labels to search recommendations

- .changeset/tasty-waves-flash.md
- packages/internet-header/src/components/post-internet-header/post-internet-header.tsx
- packages/internet-header/src/components/post-main-navigation/post-main-navigation.tsx
Added attributes recommended here: https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/
> feat(internet-header): add aria attributes to mobile menu toggle

- .editorconfig
- packages/styles/.editorconfig
Removed all the redundant config properties.
> chore: update editorconfig of styles package

- .changeset/four-shrimps-shout.md
- packages/demo/src/app/home/home.component.html
Update migration docs for Version 6 of the demo.
> docs: update migration guide v6 with precise installation instructions

- packages/styles/src/components/alert.scss
Error only appeared on the storybook visual regression testing page.
> fix(stlyes): alert action buttons for alerts

- README.md
> chore: update splash screen with new swiss post logo

- .changeset/hot-zebras-sing.md
- packages/internet-header/src/assets/js/klp-login-widget.js
@gfellerph create beta release
**Ready for review and merge!**
> fix(internet-header): fix klp-login-widget focus 

- .changeset/selfish-nails-stare.md
- packages/internet-header/src/components/post-internet-header/post-internet-header.scss
Hi folks,
could find the issue and have fixed it in post-internet-header.scss
hope it helps
> fix: add 1px to stickyness-minimal #1156

- packages/internet-header/cypress/e2e/stickyness.cy.ts
Hard to say if this helps, but let's try.
> test: fix flaky stickyness test

- .github/workflows/deploy-demo.yaml
- .github/workflows/deploy-documentation.yaml
- packages/icons/CHANGELOG.md
Account name of our bot changed
> chore: update swisspost-devs to swisspost-bot

- .changeset/metal-moose-melt.md
- packages/documentation/src/stories/getting-started/components.stories.mdx
- packages/documentation/src/stories/getting-started/styles.stories.mdx
- packages/documentation/src/stories/icons/getting-started.stories.mdx
- packages/documentation/src/stories/internet-header/getting-started.stories.mdx
- packages/documentation/src/stories/intranet-header/getting-started.stories.mdx
Some updates based on PR #1532
> chore(docs): getting started pages update

- packages/demo/.eslintrc.js
- packages/demo/.eslintrc.json
> fix(demo): tsconfig defined path in eslint should be from the root

- packages/documentation-v7/src/stories/components/alert/alert.demo.stories.ts
- packages/documentation-v7/src/stories/components/alert/alert.docs.mdx
fix: Invalid DOM property `class`. Did you mean `className`?
> fix(documentation-v7): invalid use of class with react

- .github/workflows/fetch-icons.yaml
We have a misterious committer with invalid email address.
Figured out that it's the icon pr :smile:.
> chore: fix icon pr commit author

- packages/icons/package.json
- packages/icons/src/utilities/downloadSVG.ts
- packages/icons/svgo.config.ts
- pnpm-lock.yaml
Types from SVGO makes the command `pnpm test` failing
> fix(icons): fix icons types with latest SVGO version to unlock tests

- .github/CODEOWNERS
Maintainers should come at the end.
> chore: update codeowners again

- .changeset/shaggy-avocados-provide.md
Add changeset for https://github.com/swisspost/design-system/pull/1956
> fix(demo): ngbootstrap links NaN

- pnpm-lock.yaml
Reverts swisspost/design-system#2005
> Revert "chore(*): update-browserslists"

- packages/documentation/package.json
- pnpm-lock.yaml
Fix https://github.com/cypress-io/cypress/discussions/27924 that appears in all my last PRs
> chore(documentation): Downgrade Cypress from 13.2.0 to 12.17.4

- packages/documentation/.storybook/blocks/footer.tsx
changes the background of the footer to match the footer of the demo
> fix(documentation): changes background of the footer

- .changeset/modern-zebras-drive.md
- packages/demo/src/app/bootstrap/components/form-control/form-control-demo-page/form-control-demo-page.component.html
- packages/demo/src/app/bootstrap/components/form-file/form-file-demo-page/form-file-demo-page.component.html
- packages/demo/src/app/bootstrap/components/form-select-multiple/form-select-multiple-demo-page/form-select-multiple-demo-page.component.html
- packages/demo/src/app/bootstrap/components/form-select/form-select-demo-page/form-select-demo-page.component.html
- packages/demo/src/app/bootstrap/components/form-textarea/form-textarea-demo-page/form-textarea-demo-page.component.html
- packages/demo/src/app/bootstrap/components/forms/forms-demo-page/forms-demo-page.component.html
- packages/documentation/src/stories/components/input/input.docs.mdx
- packages/documentation/src/stories/components/input/input.stories.ts
- packages/documentation/src/stories/components/select/select.docs.mdx
- packages/documentation/src/stories/components/select/select.stories.ts
- packages/documentation/src/stories/components/textarea/textarea.docs.mdx
- packages/documentation/src/stories/components/textarea/textarea.stories.ts
adds deprecation alerts for `.form-control-rg` and `.form-control-md` as well as `.form-select-rg` and `.form-select-md` to documentation and demo
> chore: adds deprecation alerts

- .changeset/giant-forks-exercise.md
- packages/styles/src/components/tabs/_tab-title.scss
Fixed from https://github.com/swisspost/design-system/pull/1181/files#diff-f4de113242b5d64ec978f4e06c6c93c9d4d4d5622e8fe8befadb3ca9450cbc0cL43-L60
> fix(styles): Active tab should have border

- packages/documentation/src/stories/components/choice-card/choice-card.ts
> fix(documentation): Choice-card doesn't have proper input name

- .changeset/four-gifts-watch.md
- packages/documentation/src/stories/components/checkbox/checkbox.docs.mdx
- packages/documentation/src/stories/components/checkbox/checkbox.snapshot.stories.ts
- packages/documentation/src/stories/components/checkbox/checkbox.stories.ts
- packages/documentation/src/stories/components/radio/radio.docs.mdx
- packages/documentation/src/stories/components/radio/radio.snapshot.stories.ts
- packages/documentation/src/stories/components/radio/radio.stories.ts
- packages/styles/src/components/form-check.scss
- packages/styles/src/components/form-validation.scss
- packages/styles/src/variables/components/_form-check.scss
- packages/styles/src/variables/components/_form-validation.scss
Reverts swisspost/design-system#2067
> Revert "fix(styles): Small variants for checkbox and radio"

- packages/internet-header/src/services/config.service.ts
- packages/internet-header/src/services/language.service.ts
- packages/internet-header/src/services/route.service.ts
Fixes linting issues in the internet header package that came up with the new rules.
> chore(header): fix linting issues

- packages/components/package.json
- packages/documentation/package.json
- pnpm-lock.yaml
Reverts swisspost/design-system#2321
> Revert "fix(components): stencil unit test require puppeteer"

- packages/components/package.json
- pnpm-lock.yaml
Reverts swisspost/design-system#2323
> Revert "fix(components): stencil unit test by installing jest-environement-node"

- packages/components/jest.config.js
Reverts swisspost/design-system#2324
> Revert "fix(components): stencil unit test by adding jest.config.js"

- packages/components/package.json
- packages/internet-header/package.json
- pnpm-lock.yaml
To fix unit tests that failing with stencil/core > 4.6.0
> fix(unit): Upgrade to Jest 29

- .changeset/gorgeous-ties-help.md
- packages/demo/src/app/common/footer/footer.component.html
- packages/documentation/.storybook/blocks/footer.tsx
I didn't find a simple way to generate it or inject through Vite, and adding js seems cumbersome
> fix(docs): Update copyright year to 2024

- .github/workflows/deploy-demo.yaml
- .github/workflows/deploy-documentation.yaml
- packages/documentation/src/stories/components/accordion/accordion.docs.mdx
fixes syntax of previous fix #2558
> feat(depoy): test update netiflyv16

- .github/workflows/deploy-documentation.yaml
Preview URL have been changed in https://github.com/swisspost/design-system/pull/2071
> chore(*): Revert change on preview URL

- .idea/scopes/Components.xml
- .idea/scopes/Components_angular.xml
- .idea/scopes/Components_react.xml
- .idea/scopes/Demo.xml
- .idea/scopes/Documentation.xml
- .idea/scopes/Icons.xml
- .idea/scopes/Internet_header.xml
- .idea/scopes/Intranet_header.xml
- .idea/scopes/Migrations.xml
- .idea/scopes/Styles.xml
In Intellij, it allows restricting a search to a specific package more easily.
> chore(intellij): Define scope for each package

- packages/internet-header/cypress/e2e/logout.cy.ts
No need to acutally click on the logout link, just ensure it's there.
> chore(test): update logout test

- CONTRIBUTING.md
Current definition of done:
- Short introduction
- Canvas for showcasing
- Controls for the showcase
- Variants if applicable (e.g. group of component or small example in context)
- Instructions for installation
- Possibility to showcase and test all variants of the component. This enables re-usage of the docs programmatically for visual regression testing.
- Accessibility hints for relevant controls like disabled state or hidden labels
- Cross browser testing of the docs (official Post supported browsers -> https://github.com/swisspost/design-system/blob/main/packages/styles/.browserslistrc)
- Testing the High Contrast mode
- Approval by UX for the story
- Screen reader testing (at least nvda+win)
- `aria-hidden="true"` or `span.visually-hidden` labels for all icons
- No react related …
> chore(contribution.md): adds definiton of done

- .github/workflows/snapshot-tests.yaml
Try to run visual regression tests on every push to the changeset-release/main branch
> chore: update snapshot-tests.yaml

- .changeset/long-hats-allow.md
- packages/components/src/components/post-popovercontainer/post-popovercontainer.scss
- packages/components/src/components/post-popovercontainer/post-popovercontainer.tsx
* Set the same border-width between the border of the tooltip and the borders that shape the arrow, and adjust offset
* Change border according to position of the arrow to always have an arrow pointing to the outside.
> fix(components): Improve display of tooltip arrow in HCM

- packages/components/src/components.d.ts
- packages/components/src/components/post-rating/readme.md
Clean up after merging the rating component.
> chore: clean build

- packages/components/src/components/post-rating/post-rating.scss
> fix(components): post-rating scss deprecation warning on unary operator

- packages/demo/src/app/post-sample/components/custom-select/custom-select-floating-demo/custom-select-floating-demo.component.html
https://sonarcloud.io/project/issues?open=AY3mTQDyUYAeUCKMCFbc&id=swisspost_common-web-frontend
> fix(demo): Custom select example label element is not bound to input

- packages/documentation/src/stories/components/forms/input/input.snapshot.stories.ts
- packages/documentation/src/stories/components/forms/input/input.stories.ts
- packages/documentation/src/stories/components/forms/radio/radio.snapshot.stories.ts
- packages/documentation/src/stories/components/forms/radio/radio.stories.ts
- packages/documentation/src/stories/components/forms/slider/slider.snapshot.stories.ts
- packages/documentation/src/stories/components/forms/slider/slider.stories.ts
- packages/documentation/src/stories/components/forms/switch/switch.snapshot.stories.ts
- packages/documentation/src/stories/components/forms/textarea/textarea.snapshot.stories.ts
- packages/documentation/src/stories/components/forms/textarea/textarea.stories.ts
Following https://github.com/swisspost/design-system/pull/2817
The tests were green when merged ?! Perhaps a cache? Anyway here are the needed fixes.
> chore(documentation): Remove ignored rule duplicate-id-aria for cypress e2e tests 2

- packages/demo/src/app/bootstrap/components/card/complex-card-demo/complex-card-demo.component.html
- packages/documentation/src/stories/components/cards/card/card.stories.ts
Last item from: https://sonarcloud.io/project/issues?open=AY3mTQBeUYAeUCKMCFbO&id=swisspost_common-web-frontend
> fix(demo, documentation): Remove redundant word "image" from the "alt" attribute of your "img" tag

- packages/documentation/cypress/snapshots/components/collapsible.snapshot.ts
Updated #2929 with additional info to fix the real bug.
> test(collapsible): temporary fix for initial animation

- .github/workflows/sonar-analysis.yaml
- sonar-project.properties
The issue was: "At least one tsconfig.json was not found in the project."
The missing file was actually part of the dependencies that needs to be installed prior to SonarCloud analysis.
> chore: add sonar workflow

- packages/documentation/.storybook/addons/version-switcher/VersionSwitcher.tsx
- packages/documentation/.storybook/addons/version-switcher/version-switcher.scss
- packages/documentation/.storybook/manager.ts
The changes for the v6 are in this PR #3049
> feat(documentation): add active state to version switch

- .github/workflows/build-tokens.yaml
- packages/tokens/tokensstudio-generated/tokens.json
How will a workflow run look?
You can see that [here](https://github.com/swisspost/design-system/actions/workflows/build-tokens.yaml).
> feat(workflows): add a build-tokens workflow

- .changeset/great-humans-talk.md
- packages/styles/src/components/form-validation.scss
Changes were already merged into v8.
> fix(styles): refactor icons declarations #3482

- packages/tokens/tokensstudio-generated/tokens.json
Reverts swisspost/design-system#3605
> Revert "chore(tokens): merge tokens into main"

- packages/tokens/tokensstudio-generated/tokens.json
chore(tokens): merge tokens into main
> chore(tokens): merge tokens into main

- packages/documentation/src/stories/getting-started/packages/internet-header/internet-header.docs.mdx
> chore(documentation): document internet-header configuration setup (#3642)

- .changeset/kind-buses-trade.md
- .changeset/popular-games-rush.md
- packages/documentation/cypress/snapshots/components/dialog.snapshot.ts
- packages/documentation/package.json
- packages/documentation/src/stories/components/dialog/dialog.docs.mdx
- packages/documentation/src/stories/components/dialog/dialog.snapshot.stories.ts
- packages/documentation/src/stories/components/dialog/dialog.stories.ts
- packages/documentation/src/stories/components/dialog/samples/js-form-data.ts
- packages/documentation/src/stories/components/modal/modal.docs.mdx
- packages/documentation/src/stories/components/modal/modal.stories.ts
- packages/documentation/src/stories/components/notification-overlay/notification-overlay.docs.mdx
- packages/documentation/src/stories/components/notification-overlay/notification-overlay.stories.ts
- packages/migrations/package.json
- packages/styles/src/components/_index.scss
- packages/styles/src/components/dialog.scss
- packages/styles/src/variables/_animation.scss
Styles for the dialog element, replacing ngb-modal.
---------
> feat(documentation,styles): adding styles for native dialog (v8)

- packages/documentation/vite.config.js
- packages/styles/gulpfile.js
- pnpm-lock.yaml
> chore: remove mixed-decls build configs

- packages/components/src/index.html
- packages/styles/src/elements.scss
Add tokens and element styles to the component playground
> chore: update components playground with tokens

- packages/tokens/tokensstudio-generated/tokens.json
Merge this PR to update the tokens in the main branch.
> chore(tokens): 🎨 update tokens

- .github/ISSUE_TEMPLATE/component-v2.yml
This PR is adding a design tasks section to the component v2 issue template.
> chore: update component issue template

- packages/components/src/components/post-menu-trigger/post-menu-trigger.tsx
> fix(post-menu-trigger): ensure compatibility with shadow DOM for menu lookup

- packages/tokens/tokensstudio-generated/tokens.json
This reverts commit 7b08f600dd13b0a202c78f254eb6315f88e51d5d.
> fix: revert "chore(tokens): 🎨 update tokens (#4090)" 

- .changeset/clean-windows-think.md
- packages/components/src/components/post-tooltip/post-tooltip.tsx
> fix(components): delayed tooltip shown even after blur event (#4053)

- packages/styles/index.html
- packages/styles/playground.js
- packages/styles/src/elements/body.scss
- packages/styles/src/palettes/_mixins.scss
- packages/styles/vite.config.js
Adds more specific token selects and fixes the preview, also adds compatibility for the `sass-embedded` package.
> chore(styles): fixes playground

- packages/documentation/src/stories/components/header/components/header.markup.ts
- packages/documentation/src/stories/components/header/header.docs.mdx
- packages/documentation/src/stories/components/header/header.stories.ts
This initial story only contains markup for the header. Options and other controls can be added later.
> feat(docs): added basic header story

- .changeset/nervous-lizards-laugh.md
- packages/styles/src/index.scss
- packages/styles/src/layouts/portal/_index.scss
- packages/styles/src/layouts/portal/_subnavigation.scss
- packages/styles/tests/layouts/portal/index.test.scss
> chore(styles): remove deprecated portal styles

- package.json
Use node download page to install it on your local machine:
https://nodejs.org/en/download
After merge:
> chore: update nodejs to latest lts

- .github/actions/setup-pnpm/action.yaml
Output the current installed versions, instead of just outputting the input values.
> fix: gitub action setup-pnpm

- .changeset/happy-needles-repeat.md
- packages/styles/src/elements/reset.scss
This is a progressive enhancement and provides the basics to use this newly available feature where it's available. No critical functionality should be built with this, only use it to enhance components.
> feat: allow transitions from and to height auto

- .changeset/heavy-tips-share.md
Fixes wrong changeset, which was added here https://github.com/swisspost/design-system/pull/4627/files
> chore: update changeset

- .changeset/fresh-hats-do.md
- packages/components/src/components/post-header/post-header.tsx
> fix(components): disconnectedCallback on `post-header` to avoid side effects on routing

- .github/ISSUE_TEMPLATE/base_component.md
Added an issue template for base component issues
> chore: Create base_component.md

- pnpm-lock.yaml
> fix: Update pnpm-lock.yaml

- .github/ISSUE_TEMPLATE/base_component.md
> chore: Update base_component.md

- .github/ISSUE_TEMPLATE/component_design.md
- .github/ISSUE_TEMPLATE/component_tokens.md
Adds issue templates for design and token tasks.
---
> feat: add new issue templates for design and tokens

- .github/ISSUE_TEMPLATE/component_styles.md
Adds an issue template for adding HTML/CSS components to the styles package. Should be used as sub-issue to the base-component template.
> chore: Create component_styles.md

- .changeset/rich-sheep-dress.md
- packages/documentation/.storybook/blocks/beta-banner.tsx
- packages/documentation/.storybook/blocks/layout/layout.scss
- packages/documentation/.storybook/blocks/layout/layout.tsx
- packages/documentation/.storybook/styles/preview.scss
Added a beta banner on each page of the documentation to tell users that v9 is still in beta.
> chore(documentation): add beta disclaimer

- packages/components/src/components/post-accordion-item/post-accordion-item.scss
- packages/components/src/components/post-accordion/post-accordion.scss
- packages/components/src/components/post-back-to-top/post-back-to-top.scss
- packages/components/src/components/post-breadcrumb/post-breadcrumb.scss
- packages/components/src/components/post-card-control/post-card-control.scss
- packages/components/src/components/post-header/post-header.scss
- packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
- packages/components/src/components/post-megadropdown/post-megadropdown.scss
- packages/components/src/components/post-popovercontainer/post-popovercontainer.scss
Replaced all top, bottom, right, and left properties with their block or inline equivalent for consistency.
---
> chore(components): use block and inline properties

- .changeset/popular-otters-rhyme.md
- packages/documentation/src/stories/components/stepper/stepper.docs.mdx
- packages/documentation/src/stories/components/stepper/stepper.stories.ts
- packages/styles/src/components/stepper.scss
Cherry-pick fix on stepper firefox
> fix(documentation): stepper progress on firefox

- .changeset/honest-mayflies-exercise.md
- packages/demo/src/app/home/home.component.html
- packages/documentation/src/stories/foundation/typography/typography-standalone.sample.css
- packages/documentation/src/stories/foundation/typography/typography.docs.mdx
- packages/documentation/src/stories/home.docs.mdx
- packages/styles/src/components/fonts.scss
- packages/styles/src/variables/_options.scss
- packages/styles/src/variables/_type.scss
> feat: update font v7

- .changeset/honest-mayflies-exercise.md
- packages/demo/src/app/home/home.component.html
- packages/documentation/.storybook/styles/themes.ts
- packages/documentation/src/stories/foundation/typography/typography-standalone.sample.css
- packages/documentation/src/stories/foundation/typography/typography.docs.mdx
- packages/documentation/src/stories/home.docs.mdx
- packages/internet-header/src/styles.scss
- packages/styles/src/components/fonts.scss
- packages/styles/src/variables/_options.scss
- packages/styles/src/variables/_type.scss
> feat: update font v6

- .github/workflows/fetch-icons-v8.yaml
- .github/workflows/fetch-icons.yaml
This PR replaces the compromised tj-actions/changed-files by its uncompromised equivalent provided by step-security in all icon workflows.
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
---
> chore: replace tj-actions/changed-files by step-security/changed-files

- packages/components/cypress/e2e/menu-button.cy.ts
- packages/components/cypress/fixtures/post-menu.test.html
Introduced new test cases for multiple triggers and menus, ensuring independent toggling and correct visibility behavior for `post-menu` component.
> chore(tests):  enhance the e2e test coverage for the `post-menu` component

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Updated issues template for feature request and bug report to have comments instead of text in sections
> chore: change from text to comment on issues templates

- packages/components/package.json
> chore(components): update clean script to remove also the generated folders in components-react and components-angular packages

- .changeset/silly-turtles-notice.md
- packages/components/src/components/post-avatar/post-avatar.tsx
This pr ensures, the component keeps working as expected, as soon as we update stencil to the next version.
---
> feat(components): prepare post-avatar component for stencil update

- .changeset/olive-kangaroos-repair.md
- packages/components/src/components/post-back-to-top/post-back-to-top.tsx
This pr ensures, the component keeps working as expected, as soon as we update stencil to the next version.
---
> fix(components): prepare post-back-to-top component for stencil update

- .changeset/perfect-camels-pay.md
- packages/components/src/components/post-tab-header/post-tab-header.tsx
- packages/components/src/components/post-tab-panel/post-tab-panel.tsx
> fix(components): prepare tab components for next stencil update

- .changeset/breezy-moose-fail.md
- packages/components/src/components/post-menu-trigger/post-menu-trigger.tsx
> fix(components): prepare post-menu-trigger component for stencil update

- .changeset/green-buckets-clap.md
- packages/components/src/components/post-card-control/post-card-control.tsx
This pr ensures, the component keeps working as expected, as soon as we update stencil to the next version.
---
> fix(components): prepare post-card-control component for stencil update

- .changeset/light-terms-knock.md
- packages/components/src/components/post-closebutton/post-closebutton.scss
- packages/components/src/components/post-closebutton/post-closebutton.tsx
Preparing the component for the stencil update
---
> feat(components): make post-closebutton component a shadow component

- .changeset/clean-bears-hammer.md
- packages/components/src/utils/environment.ts
- packages/components/src/utils/index.ts
This will help us to make our component SSR conform.
---
> feat(components): add new utility to distinguish between server and client environment

- .changeset/new-spoons-exercise.md
- packages/components/src/components/post-header/post-header.scss
- packages/components/src/components/post-header/post-header.tsx
The logo disappearing issue is caused by the missing custom property `--post-header-scroll-top` within the `--logo-height` calculation. The property has been so far set in the connectedCallback. 
When tested within the Cargo implementation:
a) on first load it works as expected
b) on language /country change the page is re-rendered but the post-header connectedCallback seems to be called before the React renders (tested with useEffect() inside the PostHeader component) and the custom property is unset.  
c) When moved to componentWillRender the custom property is set successfully.
This PR moves the handleScrollEvent function from the connectedCallback to the componentWillRender method. Additionally, a fallback value is added for the `--post-header-scroll-top` within the `--logo-height` …
> chore(components): fix logo disappearing on page locale change

- packages/components/cypress/e2e/mainnavigation.cy.ts
Update main navigation end-to-end tests that were failing because of a rounding mistake.
---
> fix(components): update main navigation e2e

- .changeset/honest-crabs-look.md
- packages/documentation/src/stories/components/stepper/stepper.docs.mdx
> chore(documentation): remove stepper banner warning

- .changeset/curly-pugs-trade.md
- packages/documentation/.storybook/styles/preview.scss
> fix(documentation): improve contrast of buttons and links of args tables

- .changeset/tidy-knives-draw.md
- packages/documentation/.storybook/styles/preview.scss
> fix(documentation): improved contrast of expandable in args table

- .changeset/three-experts-repair.md
- packages/documentation/.storybook/styles/components/banner.scss
- packages/documentation/src/shared/nb-bootstrap/ngb-component-banner.mdx
- packages/documentation/src/stories/foundations/layout/columns/columns.docs.mdx
- packages/documentation/src/stories/foundations/layout/grid/grid.docs.mdx
- packages/documentation/src/stories/foundations/typography/list/list.docs.mdx
- packages/documentation/src/stories/guidelines/shadowdom-parts/shadowdom-parts.docs.mdx
- packages/documentation/src/stories/packages/internet-header/internet-header.docs.mdx
- packages/documentation/src/stories/utilities/display/display.docs.mdx
- packages/documentation/src/stories/utilities/opacity/opacity.docs.mdx
- packages/documentation/src/stories/utilities/spacing/spacing.docs.mdx
Updated the heading hierarchy in the documentation to have a consistent one.
> fix(documentation): accessible heading hierarchy

- .changeset/sharp-suits-sparkle.md
- packages/documentation/.storybook/styles/preview.scss
> fix(documentation): add outline on links in lists

- .changeset/fuzzy-feet-ring.md
- packages/styles/src/components/form-input.scss
- packages/styles/src/components/form-select.scss
- packages/styles/src/components/form-textarea.scss
> fix(styles): floating labels iOS above the header

- .changeset/honest-apes-hammer.md
- packages/components-react/package.json
Fixes path to types for the component-react package.
> fix(components-react): fixed types path

- .github/workflows/stale.yaml
Fixed duplicate permissions definition.
> chore: Update stale.yaml

- .changeset/cuddly-clocks-arrive.md
- packages/documentation/src/stories/getting-started/developer/developer.docs.mdx
> fix(documentation): set `scope` to correct `th` tag

- .changeset/polite-rice-roll.md
- packages/intranet-header-workspace/projects/intranet-header/package.json
- packages/intranet-header-workspace/projects/intranet-header/src/lib/swisspost-intranet-header.component.ts
- pnpm-lock.yaml
This PR updates the `@swisspost/design-system-intranet-header` to be compatible with Angular 19.
---
> chore(intranet-header): migrate to Angular 19

- .changeset/cloudy-day.md
- .changeset/rainy-day.md
- .changeset/sunny-day.md
- packages/components-angular/projects/consumer-app/src/app/routes/home/home.component.html
- packages/components/cypress/e2e/tooltip.cy.ts
- packages/components/cypress/fixtures/post-tooltip.test.html
- packages/components/src/components.d.ts
- packages/components/src/components/post-popovercontainer/post-popovercontainer.scss
- packages/components/src/components/post-popovercontainer/post-popovercontainer.tsx
- packages/components/src/components/post-popovercontainer/readme.md
- packages/components/src/components/post-tooltip-trigger/post-tooltip-trigger.scss
- packages/components/src/components/post-tooltip-trigger/post-tooltip-trigger.tsx
- packages/components/src/components/post-tooltip-trigger/readme.md
- packages/components/src/components/post-tooltip/post-tooltip.scss
- packages/components/src/components/post-tooltip/post-tooltip.tsx
- packages/components/src/components/post-tooltip/readme.md
- packages/components/src/index.ts
- packages/documentation/src/stories/components/tooltip/tooltip-trigger.stories.ts
- packages/documentation/src/stories/components/tooltip/tooltip.docs.mdx
- packages/documentation/src/stories/components/tooltip/tooltip.stories.ts
- packages/styles/src/mixins/_animation.scss
> feat(component): post-tooltip refactor to improve structure, accessibility, and performance

- .changeset/config.json
- .github/workflows/release.yaml
This PR correctly configure the release/v9 branch for a release.
---
> chore: update release branch references

- .changeset/sweet-owls-laugh.md
- packages/documentation/src/stories/getting-started/migration-guide/migration-guide.docs.mdx
- packages/documentation/src/stories/getting-started/migration-guide/migrationv7-8.component.ts
- packages/documentation/src/stories/getting-started/migration-guide/migrationv8-9.component.ts
- packages/documentation/src/stories/getting-started/migration-guide/setup.component.ts
Migration guide for the new v9 version (Angular 19 + PrimeNG 19)
---
> chore(docs): add migration guide for v9

- .changeset/chubby-planes-appear.md
- packages/documentation/src/stories/misc/migration-guide/migration-guide.docs.mdx
- packages/documentation/src/stories/misc/migration-guide/migrationv7-8.component.ts
- packages/documentation/src/stories/misc/migration-guide/migrationv8-9.component.ts
- packages/documentation/src/stories/misc/migration-guide/migrationv9-10.component.ts
- packages/documentation/src/stories/misc/migration-guide/setup.component.ts
> chore(docs): add migration v8 -> v9 + rename v9 -> v10

- .changeset/mighty-tables-play.md
- packages/documentation/src/stories/packages/styles/styles.docs.mdx
The styles package version has been updated to reflect the new versions.
---
> chore(docs): update styles package info

- packages/components/src/components.d.ts
- packages/components/src/components/post-card-control/readme.md
Adds autogenerated files missing from previous merge.
> chore(components): add missing autogenerated files

- packages/documentation/.storybook/blocks/footer.tsx
> chore(docs): update team members in footer (cherrypick to v8)

- .changeset/shaggy-pears-drive.md
- packages/documentation/.storybook/blocks/eol-banner.tsx
- packages/documentation/.storybook/blocks/layout/layout.scss
- packages/documentation/.storybook/blocks/layout/layout.tsx
- packages/documentation/.storybook/styles/preview.scss
Added a End-of-life deprecation banner to the design system pages.
> chore(docs): add EOL banner

- .changeset/light-flowers-live.md
- .changeset/tidy-horses-wink.md
> chore(components): update changesets for #5469

- .changeset/legal-paws-rush.md
The class names have been changes, which is a breaking change.
---
> chore: update interactive list changeset

- .changeset/forty-rings-refuse.md
- packages/documentation/src/stories/getting-started/packages/styles-primeng/styles-primeng.docs.mdx
Cherrypick of https://github.com/swisspost/design-system/issues/5688 to v9
---
- 🧪 I have …
> chore(docs): clarify PrimeNG package scope (cherrypick/v9)

- .changeset/quiet-things-love.md
- .npmrc
- packages/styles-primeng-workspace/projects/styles-primeng-showcase/src/app/app.component.html
- packages/styles-primeng-workspace/projects/styles-primeng-showcase/src/app/app.component.ts
- packages/styles-primeng-workspace/projects/styles-primeng-showcase/src/app/app.module.ts
- packages/styles-primeng-workspace/projects/styles-primeng/src/lib/primeng-theme/components/_datepicker.scss
- packages/styles-primeng-workspace/projects/styles-primeng/src/lib/primeng-theme/index.scss
This PR adds styles for the primeng datepicker, based on this design: https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=20098-26332&m=dev
> chore(styles-primeng-workspace): bug fix primeng data table date filter styles

- .changeset/breezy-radios-teach.md
- .changeset/cyan-crabs-full.md
- .changeset/cyan-crabs-serve.md
- .changeset/heavy-spiders-cheer.md
- .changeset/mean-eyes-agree.md
- .changeset/neat-kids-shave.md
- packages/components-angular/package.json
- packages/components-angular/projects/components/package.json
- packages/components-react/package.json
- packages/documentation/package.json
- packages/intranet-header-workspace/projects/intranet-header/package.json
- packages/intranet-header-workspace/projects/intranet-header/src/lib/swisspost-intranet-header.component.html
- packages/styles-primeng-workspace/projects/styles-primeng/package.json
- packages/styles/package.json
- pnpm-lock.yaml
This PR adds/updates the peer dependencies:
- components-angular/package.json
{ "peerDependencies": {
"@angular/common": ">=19.0.0 <20.0.0",
"@angular/core": ">=19.0.0 <20.0.0",
"@angular/forms": ">=19.0.0 <20.0.0" },
}
- components-react/package.json
{"peerDependencies": {
"react": ">=18.0.0 <20.0.0",
"react-dom": ">=18.0.0 <20.0.0"}
}
> chore(components-angular, components-react): add / update peer dependencies for angular and react / v9

- .changeset/real-friends-melt.md
- packages/documentation/.storybook/blocks/footer.tsx
Cherrypick https://github.com/swisspost/design-system/pull/5778 to release/v9 branch.
---
> chore(docs): updated spds team members in footer (cherrypick/v9)

- .changeset/sour-pumas-cough.md
> chore: adjust `post-icon` component changes to patch version for all affected packages

- .changeset/cyan-crabs-full.md
- .changeset/cyan-crabs-serve.md
> chore: standardize changeset messages for `add / update peer dependencies for angular and react / v9` PR

- .changeset/lucky-states-return.md
- packages/documentation/.storybook/blocks/footer.tsx
Added new team member's photo and informations to the footer.
> chore(docs): added new team member to footer

- .changeset/lucky-states-return.md
- packages/documentation/.storybook/blocks/footer.tsx
> chore(docs): added new team member to footer (#5935)

- .changeset/shaky-nights-drop.md
- packages/styles/src/variables/components/_notification.scss
Deleted notification-font-size-map as it no longer used.
> chore(components): deleted notification-font-size-map

- .changeset/eight-moose-wink.md
- .changeset/nice-fans-study.md
- packages/styles/CHANGELOG.md
This PR is just to fix change log entries that are incorrectly formatted. 
---
> fix: reformat incorrect change log entries

- .changeset/calm-carrots-worry.md
- packages/documentation/src/stories/misc/migration-guide/migrationv9-10.component.ts
- packages/eslint/docs/rules/html/migrations/no-deprecated-chip-filter.md
- packages/eslint/src/rules/html/migrations/index.ts
- packages/eslint/src/rules/html/migrations/no-deprecated-chip-filter.ts
- packages/eslint/test/rules/html/migrations/no-deprecated-chip-filter.spec.ts
Automigration rule for the `chip-filter` class
> feat(eslint): automigration rule for the `chip-filter`
